const bhutanDzongkhags = {
    Bumthang: {
      Chhoekhor: [
        "Chakhar",
        "Changwa",
        "Damphel",
        "Dawathang",
        "Dhur Lusibee",
        "Dhur Moen",
        "Dodrong",
        "Dorjibe",
        "Druk Dok",
        "Goling",
        "Jamphel Lhakhang",
        "Kangdok",
        "Kenchosum",
        "Kharsa",
        "Kharsum",
        "Nang Lhakang",
        "Norbugang",
        "Pangrey",
        "Pedtsheling",
        "Potola",
        "Samthang",
        "Saram",
        "Shukdak",
        "Tamshing",
        "Tashiling (Chokhor)",
        "Tendok",
        "Thangbi",
        "Torshong",
        "Zangling",
        "Zhabjethang",
      ],
      Chhumey: [
        "Bhim",
        "Buli",
        "Buli/Uru",
        "Chedeypang",
        "Choda",
        "Choongphel",
        "Domkhar",
        "Gyaltsa",
        "Nangar",
        "Pangteygoenpa",
        "Phurjoen",
        "Samtenling",
        "Terzok",
        "Tharpaling",
        "Thrometh",
        "Thrometh (Samling)",
        "Trakar",
        "Ursang",
        "Uru",
        "Urudrangbi",
        "Yamthrag",
        "Yerangbi",
        "Zhurey",
        "Zincha",
        "Zugney",
        "Zugney (Chorten Nengpa)",
      ],
      Tang: [
        "Benzabi",
        "Bezur",
        "Chhutoe",
        "Chojam",
        "Dazur",
        "Gambling",
        "Gangju",
        "Jamshong",
        "Jog",
        "Khangrab",
        "Khoyar",
        "Kidzom",
        "Kuenzangdrang",
        "Misserthang",
        "Namkha",
        "Nangnang",
        "Nimalung",
        "Pangshing",
        "Phom Drong",
        "Rimochen",
        "Sameth",
        "Shobugoenpa",
        "Tandigang",
        "Tashiling (Tang)",
        "Tralang",
        "Ugyenchholing",
      ],
      Ura: [
        "Beteng",
        "Pangkhar",
        "Shingkhar",
        "Sing-nyer",
        "Soomthrang",
        "Tansibi",
        "Ura-Charipa",
        "Ura-Tarshong",
        "Ura-Toepda",
        "Ura-Trab Krispai",
        "Tsimalakha",
      ],
    },
  
  
    Chukha: {
      Bjachho: [
        "Bjagchhog",
        "Mebisa",
        "Tashi Gatshel",
        "Tsimakha",
        "Tsimasham",
        "Wangkha",
      ],
      Bongo: [
        "Baeyuel Kunzang",
        "Boeri",
        "Bongo",
        "Chhasilakha",
        "Choongkha",
        "Damji",
        "Gedu",
        "Junglay",
        "Jurma",
        "Ketogkha",
        "Miritsemo",
        "Pakshikha",
        "Phashooma",
        "Togtokha",
        "Zamsa",
        "Watsa",
      ],
      Chapcha: [
        "Bunakha",
        "Dorgoen",
        "Gangkha",
        "Jongzhi",
        "Lang Nyelsa",
        "Metep",
        "Pagga",
        "Pagga Goenpa",
        "Rimtekha",
        "Shelgoan",
        "Sheyuel",
        "Tsamdrag",
      ],
      Darla: [
        "Chhumedlakha (Barkhey)",
        "Dangreyboog (Bich Darla)",
        "Dojangchhey (Dojangchey)",
        "Gamanang",
        "Gengu",
        "Khamaedthapang (Lower Saureni)",
        "Kimalakha",
        "Norgangtoed",
        "Nyimgang (Ghamdara)",
        "Pagshinggang (Pakshina)",
        "Rinchhentse (Gurung Goan)",
        "Samarchen (Samachin)",
        "Sharphug (Sangkhu)",
        "Sillangsa (Silley)",
        "Sinchula",
        "Tabji",
        "Tagp-thang-boog (Bich Saureni)",
        "Yagang",
      ],
      Dungna: [
        "Babana",
        "Doongma",
        "Drukdingsa",
        "Mangdokha",
        "Pangu",
        "Papaling",
        "Uezhi",
      ],
      Geling: [
        "Changeykha",
        "Dagpa",
        "Dilib",
        "Geygoen",
        "Nayekha",
        "Omchhu",
        "Tsanglina",
      ],
      Getana: [
        "Bachhu",
        "Chiyuel",
        "Daga",
        "Pangsela",
        "Phootsha",
        "Trashigang",
        "Tshebji",
      ],
      Lokchina: [
        "Aamleg",
        "Bjagchhu",
        "Chagdokha",
        "Chimongna Ka",
        "Chimongna Kha",
        "Damchekha",
        "Dofam",
        "Dolepchen",
        "Dupanang",
        "Dzedokha",
        "Lotokha",
        "Pamji",
      ],
      Metakha: [
        "Gumina",
        "Metap Goenpa Maed",
        "Metap Goenpa Toed",
        "Pangu",
        "Uekha",
      ],
      Phuentsholing: [
        "Ahalay (Dophugchen)",
        "Bosokha",
        "Chongeykha A",
        "Chonggeykha B",
        "Dajaygang",
        "Deling (Chomchey)",
        "Dophulakha",
        "Gangteng",
        "Kungkha",
        "Lingdaen",
        "Marpji (Chilauney)",
        "Pachhudrag (Pachu Dara)",
        "Pachhugang (Pachu Tar)",
        "Pachhuthang (Balden Dara)",
        "Tashidingkha",
        "Toribari",
        "Wangdue Gatshel (Ramitay)",
      ],
      Sampheling: [
        "Bamenmo (Ragaythung)",
        "Doruphug (Dhungayna)",
        "Dungkarling (Ghumauney)",
        "Gurung Dara)",
        "Karmaling (Malbasay)",
        "Khatob (Burkey)",
        "Khepaithang (Khaibatar)",
        "Pangna A",
        "Pangna B",
        "Pangna C",
        "Pedtshelnang (Pakchina)",
        "Pekarling (Pekasey)",
        "Phurpaling",
        "Rigzinling (Behitar)",
        "Sengyegang(Singi)",
        "Sonamtang (Kothiline)",
        "Thongling (Daragoan)",
        "Tshachhungnal (Ahalay)",
      ],
    },
  
    Dagana: {
      Deorali: [
        "Banglachu",
        "Chukam",
        "Dolepchen",
        "Dorona Chhewa(Thulo Dorona)",
        "Dorona Chhoongwa (Sanu Dorona)",
        "Lalidhapper",
        "Maamedthang",
        "Nedachu",
        "Nyimtola",
        "Sushithang",
      ],
      Drujeygang: [
        "Lower Pangna",
        "Lower Pangserbo",
        "Tangna",
        "Upper Pangna",
        "Upper Pangserbo",
      ],
      Gesarling: [
        "Gangjab",
        "Gesarling",
        "Phuensoomgang",
        "Samtengang",
        "Tajoog",
        "Tashithang",
      ],
      Goshi: [
        "Baleggang",
        "Dogaag",
        "Gozhi",
        "Gozhi Maed",
        "Gozhi Toed",
      ],
      Kana: [
        "Aetosi",
        "Bartsha",
        "Buchunang",
        "Dalithang",
        "Gangjab",
        "Jurugang",
        "Kanakha",
        "Kazhithang",
        "Khagochen",
        "Lhaling",
        "Lungtengang",
        "Namgaylang",
        "Nyindukha",
        "Pungzhi",
        "Tanabji",
      ],
      Karmaling: [
        "Ganglingna (Labrang)",
        "Ganglingna (Labrang)",
        "Jemthang (Balabas)",
        "Karmaling (Kerabari)",
        "Labtsakha (Deorali)",
        "Omchhu (Homa)",
        "Senchumthang (Dalbari)",
      ],
      Khebisa: [
        "Akhochen",
        "Gibsa",
        "Gumla",
        "Pasger (Paksey)",
        "Pogtog",
        "Thomgang",
      ],
      lajab: [
        "Baloong",
        "Barna",
        "Kompa",
        "Sidpa",
        "Thasa",
      ],
      "Lhamoi Zingkha": [
        "Chongsamling (Sibsooni)",
        "Kuendrelthang (Majigaon)",
        "Lhamoidzingkha (Kalikhola)",
        "Loongsilsa (Daragaon)",
        "Majathang (Lamchey)",
        "Tshaemjeena",
        "Tshaemzhi Gosa (Tshaemjeena/Devitar)",
      ],
      Nichula: [
        "Damchhunang (Allay)",
        "Dangreyboog (Bichgoan)",
        "Dramze Kesa (Katarey)",
        "Gangtokha (Daragoan)",
        "Lakpaling (Manglabarey)",
        "Nichula",
        "Nyeltshosa (Basiney)",
        "Omchhugang (Apgachi)",
        "Tsheluthang (Suntoley)",
        "Yarpheling (Solmoley)",
      ],
      Trashiding: [
        "Gangyab (Gopeni)",
        "Langchhenthang (Hathikhara)",
        "Namchagla",
        "Norbuling (Lodoma)",
        "Shamdolay",
        "Tashiding",
      ],
      Tsangkha: [
        "Babythang",
        "Gakidthang",
        "Gelegchhu",
        "Goongpa Soomchu (Tisgharay)",
        "Pateykha",
        "Rongchhu (Bandarchu)",
        "Salambi",
        "Satshamchhu (Budheychu)",
        "Tsangkha",
        "Zinchila",
      ],
      Tsendagang: [
        "Dharay",
        "Gangzur",
        "Gangzur (Panakhola)",
        "Gangzur (Shamdolay)",
        "Gangzur Maed (Salaree)",
        "Gangzur Toed (Pasebung)",
        "Norbuzhingkha",
        "Norbuzhingkha (Panakhola)",
        "Samarchu (Samakhola)",
        "Tsendagang",
        "Tsendagang (Suntoley)",
        "Yuebug (Majuwa)",
      ],
      Tseza: [
        "Jangsagang",
        "Karlingzingkha",
        "Pelling",
        "Samaed",
        "Tashigang",
        "Tongshong (Tongzho)",
        "Tsangleykha",
        "Zamtog",
      ],
    },
  
    Gasa: {
      Khamaed: [
        "Bara",
        "Barsha",
        "Bayzhina",
        "Chalakha",
        "Chasungsa",
        "Chruawog",
        "Chubdey",
        "Churaphakha",
        "Damjee",
        "Gayza",
        "Jabisa",
        "Jazhidingkha",
        "Jizhi",
        "Kabina",
        "Khailog",
        "Namphakha",
        "Potogang",
        "Selikha",
        "Tashithang",
        "Tomu",
        "Tsanakha",
        "Yeodo",
        "Yeomena",
        "Zhazhukha",
        "Zomina",
      ],
      Khatoe: [
        "Amochhu",
        "Baychhu",
        "Belpakha",
        "Chhogley",
        "Datakha",
        "Dochong",
        "Dongyebi",
        "Gathana",
        "Khailog",
        "Lungchukha",
        "Mani",
        "Neukha",
        "Nurbi",
        "Phulakha",
        "Tabchen",
        "Thangkha",
        "Tsangkha",
        "Tsebgang",
        "Tsheringkha",
        "Womchugang",
        "Yemena",
        "Zamna",
        "Zanang",
      ],
      Laya: [
        "Chongra",
        "Gayza",
        "Lubcha",
        "Lungo",
        "Neylug",
        "Pazhi",
        "Toedkor",
      ],
      Lunana: [
        "Dotag",
        "Drangsho",
        "Lhedi",
        "Raminang",
        "Relo",
        "Shangsa",
        "Tagshor",
        "Thangza",
        "Threlga",
        "Toenchoe",
        "Tshozhi",
        "Uesana",
        "Wachey",
      ],  
    },
  
  
    Haa: {
      Bji: [
        "Chenpa",
        "Choomgpa",
        "Chubarna",
        "Dongsana/Taloong",
        "Geychhukha",
        "Gungkha",
        "Gyensa",
        "Jamgoen",
        "Longlong",
        "Machina",
        "Makana",
        "Pangphu",
        "Takchugoenpa",
        "Tokey",
        "Tsenka",
        "Tsenkagoenpa",
        "Wooka",
        "Yangoen",
        "Yangthang",
        "Yetshephu",
        "Yulang",
      ],
      Gakiling: [
        "Dorithasa",
        "Fetena",
        "Gangrinmo",
        "Kowkha",
        "Ngatse",
        "Phootsena",
        "Rangtse",
        "Saidzong",
        "Sertena",
        "Ta-nga/Chigo",
        "Thangdokha",
        "Yangtse",
        "Yokha",
      ], 
      Katsho: [
        "Bali",
        "Dragding",
        "Gargkha",
        "Hatam",
        "Ingo",
        "Kargoen",
        "Karjena",
        "Mombitshokha",
        "Naktshang",
        "Namdhu",
        "Pharikha",
        "Wangtsa",
      ], 
      Samar: [
        "Balamnang",
        "Barakha",
        "Barasham",
        "Chumeyding",
        "Dorikha",
        "Jenkanang",
        "Kouna",
        "Langjogang",
        "Langpa",
        "Lhakhangchen",
        "Norbugang",
        "Phendona",
        "Pudunang",
        "Sharri",
      ],   
    },
  
    Lhuentse: {
      Gangzur: [
        "Amchi",
        "Changray",
        "Chhesa",
        "Denkaling",
        "Dhuthay",
        "Gangzur",
        "Jalamzur",
        "Jang",
        "Khamphu",
        "Khaujoong",
        "Kyidloong",
        "Lekpa",
        "Lingabi",
        "Magar",
        "Namseygang",
        "Napzala",
        "Ney",
        "Ngar/Nyar",
        "Nyimzhong",
        "Phatala",
        "Rotpa",
        "Samling",
        "Sapho",
        "Shawa",
        "Shomshing",
        "Tagzibar",
        "Tangsa",
        "Taushing",
        "Taushinggoenpa",
        "Thimyul",
        "Thrima",
        "Tongling",
        "Tsholing",
        "Youngmaling",
        "Zhamling",
      ],
      Jarey: [
        "Changkhala",
        "Jarey",
        "Kharchung/Pam",
        "Ladrong",
        "Ngang Ngae",
        "Trapashing",
        "Wayang",
        "Yabi",
        "Yumchhe",
      ],
  
      Khoma: [
        "Babtong",
        "Berpa",
        "Dragteng",
        "Gangla",
        "Goenkhar",
        "Karphu",
        "Kemtshong",
        "Khoema",
        "Kholma",
        "Khoma",
        "Laber",
        "Lawa",
        "Lukchu",
        "Nyalamdung",
        "Pangkhar",
        "Pengtse",
        "Rolmateng",
        "Serphu",
        "Taya",
        "Tsang-ngo",
        "Zangkhar",
      ],
  
      Kurtoed: [
        "Arjhaling",
        "Chagdzom",
        "Chaktamin",
        "Chhanyalgang",
        "Chhusa",
        "Chongsa",
        "Churchuma",
        "Darjaygang",
        "Dongmaed",
        "Drabling",
        "Dungkar",
        "Garong",
        "Goshingpang",
        "Gurta",
        "Jangtse",
        "Jasabi",
        "Lamsabi",
        "Lamsaykapa",
        "Maenbi",
        "Nagling",
        "Nyaray",
        "Pirbee",
        "Ruling",
        "Serphu",
        "Sershong",
        "Sewel",
        "Shangthongling", 
        "Shauzhong",
        "Signar",
        "Sugpee",
        "Sumdhang",
        "Tabi",
        "Tagdzong",
        "Takharme",
        "Taling",
        "Tangroong",
        "Tergang",
        "Thangbi",
        "Thongjaling",
        "Thowa",
        "Thuenpey",
        "Tongmay",
        "Uygenphoog",
        "Wamdrang",
        "Wawel",
        "Zimpong",
        "Zongsar",
      ],
  
      Menbi: [
        "Bamendrangsa",
        "Bariphu",
        "Boushong",
        "Bumpashing",
        "Chalibi",
        "Chengaling",
        "Dangling",
        "Dangsangoenpa",
        "Dosagang",
        "Dromzhong",
        "Dungkardowa",
        "Gamshing",
        "Gangkhar",
        "Garapho",
        "Gorgan",
        "Kamdhar",
        "Kasithang",
        "Katog",
        "Khampaling",
        "Kharsa",
        "Khashaling",
        "Khochen",
        "Kimphay",
        "Kusumphay",
        "Langphog",
        "Larjab",
        "Ledong",
        "Lekpagang",
        "Lugarpang",
        "Maenjabi",
        "Manigang",
        "Moormo",
        "Nadrang",
        "Namdang",
        "Namnangbi",
        "Ngamaling",
        "Nyaibi",
        "Oumzor",
        "Pangsar",
        "Pelrigoenpa",
        "Petsizor",
        "Phagidroong",
        "Phungshingang",
        "Rawabi",
        "Rawabi Goenpa",
        "Rewaling",
        "Samcheling",
        "Samling",
        "Sershingbi",
        "Shangrabi",
        "Shormaed",
        "Tagmochhu",
        "Takayla",
        "Tangpa",
        "Tashiling",
        "Thekcholing",
        "Thongjaling",
        "Tongmakhar",
        "Tsampdemo",
        "Tungkhar",
        "Yanglagoenpa",
        "Yomaed",
        "Youngrab",
        "Youngshingphel",
        "Zarthang",
        "Zarthang Goenpa",
        "Zhungkhar",
        "Zungphu",
      ],
  
      Metsho: [
        "Balam",
        "Balam/Nimalawa",
        "Bamdhir",
        "Changchen",
        "Changshinpokpa",
        "Dowaletang",
        "Drukla",
        "Dulebi",
        "Gongdar",
        "Gortshom",
        "Gulipang",
        "Janakchen",
        "Kermademo",
        "Khenye Lhakhang",
        "Lhakhangtshawa",
        "Mangdhir",
        "Mukpakhar",
        "Obi",
        "Oonggar",
        "Pangshingmey",
        "Pholadowa",
        "Samdang",
        "Serbuchuka",
        "Singyebi",
        "Tachung",
        "Thangthrom Maed",
        "Thangthrom Maed Goenpa",
        "Tongthrong",
        "Tonzibi",
        "Tshochen",
        "Tshodrang",
        "Waney",
        "Yamalung Goenpa",
        "Yokpaling",
        "Yozer Goenpa",
        "Yurung",
        "Zhongmaed",
      ],
  
      Minjay: [
        "Amdrangchhu",
        "Boo-dur",
        "Chengling",
        "Chusa",
        "Dhokpabi",
        "Draag-gong",
        "Draag-gong Goenpa",
        "Draledowa",
        "Jabum",
        "Jalang",
        "Keroo",
        "Kupi-nyalsa",
        "Legchugang",
        "Legpachu",
        "Legshogang",
        "Minjey",
        "Nyaka",
        "Phangchenbi",
        "Pumogang",
        "Sershing",
        "Tongling",
        "Wangzhing",
        "Zham",
      ],
  
      Tsenkhar: [
        "Artobadeb",
        "Autho",
        "Bangtsho",
        "Barchhu",
        "Changchang Goenpa",
        "Changmadung",
        "Chharbi",
        "Chim Gong",
        "Chowa",
        "Chulung",
        "Chungkha",
        "Dagarthang",
        "Dekaling",
        "Domkhar",
        "Dongling",
        "Dongthrom",
        "Gamanang",
        "Genchungla",
        "Godong/Gordong",
        "Go-nyid",
        "Guengdrang",
        "Jarkang",
        "Kawachen",
        "Khablang",
        "Kharphu",
        "Kiphung",
        "Lagay",
        "Langabi",
        "Lawsa",
        "Ngathung",
        "Peldraphu",
        "Phomed-doong",
        "Phowantay",
        "Phuntshochhoeling",
        "Phurshongang",
        "Sangphu",
        "Shermachhu",
        "Shermachhu Goenpa",
        "Sokarom",
        "Sokchen",
        "Takchu",
        "Tashi Ling",
        "Toekhar",
        "Tongphugang",
        "Tongsheling",
        "Tongshi Lung",
        "Trangka Shing",
        "Tsaenkhar",
        "Tshangphu",
        "Tshochim",
        "Tsholadrang",
        "Tsochhen",
        "Umling",
        "Wambur",
        "Yangla",
        "Yanglong",
      ],
    },
  
    Mongar: {
      Balam: [
        "Bahkaphai ",
        "Balam ",
        "Jadoong ",
        "Jadoong Goenpa ",
        "Jadoong Kha ",
        "Khebishing ",
        "Sangjuzor ",
        "Selkhar",
      ],
  
      Chali: [
        "Aagshaling ",
        "Aidurla ",
        "Bakhim ",
        "Balingbi ",
        "Bameijangsa ",
        "Bana ",
        "Barigoila ",
        "Barleng ",
        "Bewling ",
        "Bolipang ",
        "Budishing ",
        "Chagsar ",
        "Changmashing ",
        "Charzhong ",
        "Chaukileng ",
        "Chawasing ",
        "Chewang ",
        "Chhaling ",
        "Chulabi ",
        "Damaling ",
        "Darseng ",
        "Dogtang ",
        "Dokorbang ",
        "Domangla ",
        "Dongjug ",
        "Dongtoed ",
        "Dongtoed Bakhim ",
        "Dopang ",
        "Dopang ",
        "Gensing ",
        "Goensar ",
        "Gorsum ",
        "Gortongla ",
        "Jachuling ",
        "Jambi ",
        "Japang ",
        "Kadam ",
        "Kampasadong ",
        "Kamsa ",
        "Kawakhoi ",
        "Khachorshing ",
        "Khampaje ",
        "Kharduma ",
        "Kharigab ",
        "Kharigab ",
        "Khartong ",
        "Khemsang ",
        "Khoijongla ",
        "Khoilajong ",
        "Kirzhong ",
        "Kotshome ",
        "Kurzam ",
        "Lhakang ",
        "Lhakang Bana ",
        "Lhakang Dongbar ",
        "Lhakang Goenshing ",
        "Lhakang Khoyur ",
        "Lhakang Lingchung ",
        "Lhakang Pangjab ",
        "Lhakang Ringseng ",
        "Lhakang Ringseng ",
        "Lhakang Sokpaling ",
        "Lhakang Tengpa ",
        "Lhakang Unakhang ",
        "Lungkang ",
        "Masangkangjay ",
        "Mentshang ",
        "Nagtshang ",
        "Nagtshangwog ",
        "Namabi ",
        "Namathang ",
        "Namling ",
        "Nordangsa ",
        "Numabiwang ",
        "Nyerpa ",
        "Oangthang Chungku ",
        "Pangjagpa ",
        "Pangshing ",
        "Pangthang ",
        "Pangthang ",
        "Pangthang ",
        "Pangthang Shokposeng ",
        "Pemagayser ",
        "Phachaphogchi ",
        "Phodagnma ",
        "Phumazur ",
        "Pogtor ",
        "Rahambi ",
        "Remochhu ",
        "Rolmochhu ",
        "Salapho ",
        "Sapogtor ",
        "Shebchi ",
        "Shingkharzhong ",
        "Shogoseng ",
        "Sogpaling ",
        "Sumthuen ",
        "Tadzong ",
        "Tagling ",
        "Tagling ",
        "Tashipoktor ",
        "Thangthala ",
        "Thempang ",
        "Tikusalung ", 
        "Toepaphu ",
        "Torzhonggor ",
        "Trashikhangsar ",
        "Tshamkhang ",
        "Tshangkhar ",
        "Tshepadong ",
        "Tshokila ",
        "Usdur ",
        "Wang ",
        "Wangkhar ",
        "Yangthang ",
        "Yoekhoi ",
        "Yoekhoi ",
        "Yoezer Pangthang ",
        "Yontenkhem ",
        "Zanglawang ",
        "Zhongje ",
        "Zhongje ",
        "Zhongkey ",
        "Zinthuen",
      ],
  
      Chaskhar: [
        "Chagsakhar ",
        "Doongshingma ",
        "Khamang ",
        "Pam ",
        "Yangrapoongshing ",
        "Yetong",
      ],
  
      Drametse: [
        "Bazor ",
        "Bikhar ",
        "Dramdetse ",
        "Gashari ",
        "Gobka ",
        "Jiwa ",
        "Laymey ",
        "Laymey Serkhagphoog ",
        "Luwang ",
        "Ngarphai ",
        "Ngarphel ",
        "Ongkhar ",
        "Phentshomo ",
        "Serkhaphug ",
        "Shadang ",
        "Shaphangma ",
        "Thoongdabi ",
        "Thoongdari ",
        "Thramlo ",
        "Waichur ",
        "Yalum ",
        "Yengkhartshing ",
        "Zangkhar",
      ],
  
      Drepong: [
        "Chhagsuzor ",
        "Drepoong ",
        "Labtsa Ka ",
        "Labtsa Kha ",
        "Tsangkhar ",
        "Zunglen",
      ],
  
      Gongdue: [
        "Baagla ",
        "Baagla Edi ",
        "Baagla Goenpa ",
        "Baagla Khimong ",
        "Bangbangla ",
        "Bogarbi ",
        "Chaibi ",
        "Daagsa ",
        "Damkhar ",
        "Dekhar ",
        "Dengkaling ",
        "Dewabi ",
        "Dogmo ",
        "Goenpa ",
        "Gorgdey ",
        "Gorthongla ",
        "Gungdue ",
        "Kormaed ",
        "Kumadzong ",
        "Labtsa ",
        "Mantshang ",
        "Miden ",
        "Pangthang ",
        "Pangtong ",
        "Phadzong ",
        "Phosala ",
        "Phuchung Goenpa ",
        "Pikari ",
        "Salibi ",
        "Salibi Dungda ",
        "Toedkar ",
        "Tshabor ",
        "Tshambali ",
        "Weringla",
      ],
  
      Jurmey: [
        "Aring Daza ",
        "Awatang ",
        "Bacha ",
        "Bacha ",
        "Barlamtoed ",
        "Barpoong ",
        "Baydengyer ",
        "Bilam ",
        "Bumnali ",
        "Chagpa ",
        "Chenchari ",
        "Dangkila ",
        "Daroong ",
        "Dekilam ",
        "Doongkar ",
        "Doongmein ",
        "Dori ",
        "Dumdey ",
        "Gamong ",
        "Ganggarthang ",
        "Gaykhar ",
        "Gomtshanglo ",
        "Gongtshang ",
        "Kaikhar ",
        "Kangloong ",
        "Karmaling ",
        "Khemtagpa ",
        "Kognala ",
        "Korkhang ",
        "Korphu ",
        "Kurtakay ",
        "Langabi ",
        "Luzor ",
        "Maentsang ",
        "Maniling ",
        "Maphai ",
        "Menchaphoog ",
        "Moodoongbi ",
        "Moodoongkhar ",
        "Moogtangkhar ",
        "Ngamphoog ",
        "Ngangri ",
        "Orkawang ",
        "Pangkang ",
        "Pangthang ",
        "Pangthang ",
        "Pegpela ",
        "Phaichhelo ",
        "Phentokma ",
        "Poongla ",
        "Rewang ",
        "Rimpako ",
        "Ringphu ",
        "Ringphujab ",
        "Roinangwoong ",
        "Samkhar ",
        "Sangkama ",
        "Shingmung ",
        "Shingsiri ",
        "Singyephu ",
        "Tashi Tshering ",
        "Thongpashing ",
        "Tooloogpe ",
        "Tsangkhazor ",
        "Tselam ",
        "Tselam ",
        "Tselam/Kamling ",
        "Wodang ",
        "Ya-Ragkla",
      ],
      Kengkhar: [
        "Amdaybu ",
        "Amshing Wog ",
        "Aring ",
        "Artshong ",
        "Bainang ",
        "Bargoenpa ",
        "Bargoenpa ",
        "Barzor ",
        "Chiphu ",
        "Deng ",
        "Deshingpeg ",
        "Dochhuru ",
        "Dochiru ",
        "Dogsabi ",
        "Dogtang ",
        "Dogtshong Nadang ",
        "Dongnala ",
        "Doongkargoerpa ",
        "Doongmarma ",
        "Draphu ",
        "Drongphoog ",
        "Duezawong ",
        "Ebi ",
        "Gabcha ",
        "Genchaphu ",
        "Ghishinghung ",
        "Goenpa ",
        "Gomchhu ",
        "Gunmari ",
        "Gyalkhar ",
        "Kamngeysa ",
        "Khangma ",
        "Khesigang ",
        "Khochung ",
        "Khoishing ",
        "Khurzong ",
        "Korshingngari ",
        "Kuli ",
        "Kyidpari ",
        "Kyidpari ",
        "Maenchabilam ",
        "Maentsala ",
        "Magola ",
        "Magola ",
        "Mooroong ",
        "Munma ",
        "Nadang ",
        "Nanari ",
        "Neykolog ",
        "Nugphu ",
        "Olkid ",
        "Pangthang ",
        "Pangthang ",
        "Pangthoong ",
        "Payka ",
        "Pedoongroong ",
        "Pogla ",
        "Putshume ",
        "Rishogay ",
        "Rizor ",
        "Romangla ",
        "Serkong ",
        "Shajula ",
        "Shetongbi ",
        "Shingchongri ",
        "Soichari ",
        "Suipari ",
        "Telpo ",
        "Tongkangla ",
        "Tongkangla/Sungkar ",
        "Tongkangla/Zitsibi ",
        "Tongla ",
        "Tongla Goenpa ",
        "Tongla Mangzing ",
        "Tsalabi ",
        "Tshamnagri ",
        "Tshangnari ",
        "Tshelshingtang ",
        "Tshowang ",
        "Tshowangri ",
        "Wangyer ",
        "Warongborang ",
        "Yuldagri ",
        "Zor ",
        "Zorthoong",
      ],
  
      Mongar: [
        "Barpang ",
        "Gora ",
        "Gyelpoizhing ",
        "Jalbab ",
        "Jamcholing ",
        "Kadam ",
        "Kheshirpang ",
        "Kidekhar ",
        "Koenbar ",
        "Lukpangthang ",
        "Monggar ",
        "Nagling ",
        "Nyekhang ",
        "Phosorong ",
        "Pirbi ",
        "Pirbi ",
        "Pirbi ",
        "Shongkaling ",
        "Tagchhu ",
        "Themnangbi ",
        "Trailing ",
        "Tsenglung Goenpa ",
        "Wangling ",
        "Wengkhar ",
        "Yagpoogang",
      ],
      Narang: [
        "Besipoktor ",
        "Brakhagthang ",
        "Bumpa ",
        "Chagsakhar ",
        "Chhema ",
        "Dangthung ",
        "Dengsor ",
        "Deyphung ",
        "Dongshoom ",
        "Garpamani ",
        "Gashari ",
        "Gomchhu ",
        "Gomchhuzur ",
        "Gothonpo ",
        "Hurchilo ",
        "Jomri ",
        "Khalong ",
        "Maithung ",
        "Narang ",
        "Narang Besipoktor ",
        "Narang Pangkang ",
        "Narang Phaphugpangkang ",
        "Narang Raynangkhar ",
        "Pangkhang ",
        "Pangthang ",
        "Phenzur ",
        "Phusizur ",
        "Thongkhar ",
        "Thrinangphu ",
        "Wangyer ",
        "Waphaipangthang",
      ],
      Ngatshang: [
        "Bumpazor ",
        "Goenpa ",
        "Ngatshang ",
        "Nyingala ",
        "Pelshool ",
        "Phanasi ",
        "Thoombari ",
        "Yekhar ",
        "Zangdari",
      ],
  
      Saling: [
        "Bongdeyma ",
        "Drogsar ",
        "Drogsar/Mangling ",
        "Jangdung ",
        "Kalapang ",
        "Masangdaza ",
        "Pangsibi ",
        "Resa ",
        "Saling ",
        "Seng-Gor ",
        "Thridangbi ",
        "Tshenzabi",
      ],
  
      Shermuhoong: [
        "Gangmoong ",
        "Jabgang ",
        "Muhoong ",
        "Serzhong ",
        "Shiling ",
        "Soenakhar ",
        "Thueling",
      ],
  
      Silambi: [
        "Baribang ",
        "Daag ",
        "Dekdongla ",
        "Goenpa ",
        "Gyalong ",
        "Kadag ",
        "Kadag/Salipong ",
        "Kangkangma ",
        "Kangkari ",
        "Khatoed ",
        "Khatoed/Baribang ",
        "Khatoed/Silambi ",
        "Laijuk ",
        "Nagor ",
        "Nagor Goenpa ",
        "Nagor Pang ",
        "Nagor/Pam ",
        "Pam ",
        "Pang Gyerteng ",
        "Pang Gyerteng/Goenpa ",
        "Pang Gyerteng/Phungling ",
        "Salipong ",
        "Silambi ",
        "Silambi/Lemigoenpa ",
        "Silambi/Tumdrag ",
        "Wama ",
        "Wama/Chang Changma ",
        "Yarig",
      ],
  
      Thangrong: [
        "Atola ",
        "Baucholing ",
        "Changshing ",
        "Lingkhar ",
        "Ngaru-Pongtang ",
        "Panglen",
      ],
  
      Tsakaling: [
        "Angtonyelsa ",
        "Aringtengma ",
        "Artogang ",
        "Chalgang ",
        "Chalgang/Kaling ",
        "Chalgang/Thowalsa ",
        "Chubar ",
        "Churtoog ",
        "Churtsha ",
        "Chutey ",
        "Damtshang Pokpa ",
        "Demoongla ",
        "Dokporo ",
        "Dolebtang ",
        "Dolebtang ",
        "Domula ",
        "Drenling ",
        "Drenling/Dabang ",
        "Drenling/Emalaphuk ",
        "Drenling/Gangka ",
        "Drenling/Gaptangra ",
        "Drenling/Kadamwo ",
        "Drenling/Khanakshing ",
        "Drongtoed Mawo ",
        "Gamanang ",
        "Gamanang/Loongdubi ",
        "Horong ",
        "Jangtagoen ",
        "Karshingang ",
        "Khanashing ",
        "Khashagang ",
        "Khashalbadap ",
        "Khimsang ",
        "Langabi ",
        "Legibi ",
        "Legibi ",
        "Leksingphu ",
        "Leksingphu/Bongring ",
        "Leksingphu/Churtung ",
        "Leksingphu/Dogtang ",
        "Leksingphu/Drengling ",
        "Leksingphu/Kadam ",
        "Leksingphu/Thongwang ",
        "Lewamani ",
        "Lhadrang ",
        "Loongdubi ",
        "Loongkang ",
        "Nagtshang ",
        "Norbugang ",
        "Nyartsi ",
        "Nyartsi/Shaboom ",
        "Nyartsi/Singma Nangka ",
        "Nyartsi/Tsema Nangka ",
        "Pang ",
        "Pangtshela ",
        "Paytshongbi ",
        "Paytshorgbi ",
        "Paytshorgbi/Balamchungku ",
        "Paytshorgbi/Rababi ",
        "Pherpobadap ",
        "Selwa Lhakhang ",
        "Shingmar Pokpa ",
        "Sowangtey ",
        "Tagkhambi/Barnang ",
        "Tagkhambi/Chimsaning ",
        "Tagkhambi/Dekiling ",
        "Tagkhambi/Gangka ",
        "Tagkhambi/Gendrang ",
        "Tagkhambi/Khoboom ",
        "Tagkhambi/Khomdangchhu ",
        "Tagkhambi/Kuengachhoeling ",
        "Tagkhambi/Norbugang ",
        "Tagkhambi/Pang ",
        "Tagkhambi/Wadong ",
        "Tagkhambi/Yerchung ",
        "Tagkhamtey ",
        "Talabadhap ",
        "Terkong ",
        "Tharmcharm ",
        "Thodamla ",
        "Thongzhong Goenpa ",
        "Thoomling ",
        "Thormazhong/Wadong ",
        "Threwatong ",
        "Tormazhong/Lhakhang ",
        "Tormazhong/Thongwang ",
        "Tshodrang ",
        "Wadong ",
        "Yabi ",
        "Yartogang ",
        "Zangtoong ",
        "Zhingjigpala",
      ],
  
      Tsamang: [
        "Ganglapong/Barilungpa ",
        "Ganglapong/Bongring ",
        "Ganglapong/Changchen ",
        "Ganglapong/Chaptang ",
        "Ganglapong/Darshingwog ",
        "Ganglapong/Dawashing ",
        "Ganglapong/Dechenling ",
        "Ganglapong/Gawaling ",
        "Ganglapong/Genzangtse ",
        "Ganglapong/Goenpa ",
        "Ganglapong/Goenpokpa ",
        "Ganglapong/Golitagpa ",
        "Ganglapong/Halong ",
        "Ganglapong/Jalamwog ",
        "Ganglapong/Karshingtsa ",
        "Ganglapong/Khuling ",
        "Ganglapong/Korshing ",
        "Ganglapong/Leochen ",
        "Ganglapong/Lhakhang ",
        "Ganglapong/Lowatongkang ",
        "Ganglapong/Manitakpa ",
        "Ganglapong/Ney ",
        "Ganglapong/Nyaka ",
        "Ganglapong/Pang ",
        "Ganglapong/Pangthangtoe ",
        "Ganglapong/Phuntsholing ",
        "Ganglapong/Rewochakgang ",
        "Ganglapong/Samabar ",
        "Ganglapong/Samarchen ",
        "Ganglapong/Samling ",
        "Ganglapong/Senshingbi ",
        "Ganglapong/Shoksholong ",
        "Ganglapong/Sothriling ",
        "Ganglapong/Tashiling ",
        "Ganglapong/Tashipai ",
        "Ganglapong/Tashizanglung ",
        "Ganglapong/Tebiling ",
        "Ganglapong/Thongjalingwog ",
        "Ganglapong/Thongshingtakpa ",
        "Ganglapong/Tsendentsawa ",
        "Ganglapong/Wachen ",
        "Ganglapong/Zangshingtsawa ",
        "Ganglapong/Zhenthen ",
        "Tokari ",
        "Tokari/Artang ",
        "Tokari/Augungna ",
        "Tokari/Bangdrabi ",
        "Tokari/Brengpajab ",
        "Tokari/Bumpatakpa ",
        "Tokari/Chadongbi ",
        "Tokari/Chukiduwa ",
        "Tokari/Chumetakpa ",
        "Tokari/Darchen ",
        "Tokari/Debang ",
        "Tokari/Debang ",
        "Tokari/Dekigang ",
        "Tokari/Denchen ",
        "Tokari/Draktangkhar ",
        "Tokari/Duwashing ",
        "Tokari/Gensingnyesa ",
        "Tokari/Goenpa ",
        "Tokari/Golibi ",
        "Tokari/Jalamwog ",
        "Tokari/Jewashing ",
        "Tokari/Kolokbi ",
        "Tokari/Labi ",
        "Tokari/Leochung ",
        "Tokari/Lhadrang ",
        "Tokari/Mutigang ",
        "Tokari/Nakchen ",
        "Tokari/Nakiduwa ",
        "Tokari/Nakphung ",
        "Tokari/Nambucha ",
        "Tokari/Pam ",
        "Tokari/Ralamey ",
        "Tokari/Sangcha ",
        "Tokari/Shakhar ",
        "Tokari/Shingmartakpa ",
        "Tokari/Shojabi ",
        "Tokari/Shokang ",
        "Tokari/Shungpashing ",
        "Tokari/Singyetsawa ",
        "Tokari/Sogangguto ",
        "Tokari/Sogangwog ",
        "Tokari/Sumthuen ",
        "Tokari/Tabsina ",
        "Tokari/Tashiling ",
        "Tokari/Thekarla ",
        "Tokari/Thowa ",
        "Tokari/Thowagang ",
        "Tokari/Thrachamey ",
        "Tokari/Tsangtsa ",
        "Tokari/Tshendentsawa ",
        "Tokari/Tshiden ",
        "Tokari/Umling ",
        "Tokari/Wodang ",
        "Tokari/Woktapka ",
        "Tokari/Yedhap ",
        "Tokari/Zampatakpa",
      ],
    },
  
    Paro: {
      Dokar: [
        "Bangkha",
        "Chhuzom",
        "Dala",
        "Dawakha",
        "Dzongang",
        "Gagay",
        "Gayjo",
        "Goensakha",
        "Jabisa",
        "Khamdraag",
        "Khamdraag-gang",
        "Lagel",
        "Langmikha",
        "Mendrel Jabkha",
        "Phuchhekha",
        "Sali",
        "Silu Goenpa",
        "Tamchoegang",
        "Tango",
        "Tashigang",
        "Tenchhekha",
        "Toepchugang",
        "Togtokha",
        "Tshoelgang",
        "Tshongkha",
        "Tsinakha",
        "Tsiphoog",
        "Uesakha",
        "Uesuna",
      ],
  
      Dopshari: [
        "Bamizhikha",
        "Bara",
        "Batsekha",
        "Buelchukha",
        "Changyoelkha",
        "Chimakha",
        "Damchenang",
        "Damzhi",
        "Dangribug",
        "Delikha",
        "Dorokha",
        "Dragbeylo",
        "Duezhi",
        "Hingzhiwog",
        "Jagchukha",
        "Jagchutsekha",
        "Jangonang",
        "Jangonang",
        "Jangsa",
        "Jangsa Gongm",
        "Jangsakha",
        "Jangsana",
        "Jangsuna",
        "Jipa",
        "Jizhigang",
        "Jombenang",
        "Jooka",
        "Jooka Gom",
        "Jooka Thangkha",
        "Jugang Thagchukha",
        "Karshitsha",
        "Kempa",
        "Khamshingwog",
        "Khimsabu",
        "Khimsarbu",
        "Khimsarp",
        "Kuduphoog",
        "Kuduphoog Kotsha",
        "Liwog",
        "Nazhikha",
        "Nazhikha",
        "Phalom",
        "Phenshing Zhikha",
        "Pidekha",
        "Ramnang",
        "Richhendeling",
        "Richhukha",
        "Rijoog",
        "Rijoog Tsima",
        "Rijoogkha",
        "Rimdo Kempa",
        "Rimdotshelkha",
        "Rotogang",
        "Samarkha",
        "Sephu Jizhigang",
        "Shangzhikha",
        "Tadingkha",
        "Thangkana",
        "Togtokha",
        "Tshozarkha",
        "Zharikha",
        "Zhikha",
      ],
  
      Doteng: [
        "Aa-tsho",
        "Chhubar",
        "Chingdued Goenpa",
        "Jabji",
        "Joogar",
        "Joogar Tselkha",
        "Loogchhoed",
        "Pachhu",
        "Phooshar",
        "Phunoob",
      ],
  
      Hungrel: [
        "Changsima",
        "Chhubjagkha",
        "Chukhozakha",
        "Donagmo",
        "Drukgyeling",
        "Gaupel",
        "Goenkha",
        "Hoongrelkha",
        "Jangmedna",
        "Jangsarbu",
        "Loongchhungna",
        "Nangshikha (Hungrel)",
        "Nyangmedzampa",
        "Tshongdue",
        "Zore Gone",
      ],
  
      Lamgong: [
        "Bartshik",
        "Chhukha",
        "Darkhang",
        "Dokha",
        "Gangjoog",
        "Gedda Zam",
        "Geptsha",
        "Gyedkha",
        "Jagar Thangmaed",
        "Jagathang Maed",
        "Jagathang Toed",
        "Kyidchhu",
        "Ngopa",
        "Nubri",
        "Sergang",
        "Sharhikha",
        "Shomo",
        "Soe",
        "Soe Yaksa",
        "Tsendanang",
        "Tsendonang",
        "Tsenthang",
        "Tsenthang Thangtoed",
        "Tsenthang Toed",
      ],
  
      Lungnyi: [
        "Achilakha",
        "Achilakha",
        "Atsha",
        "Baangdey",
        "Bakhimnang",
        "Bameynyikha",
        "Bara",
        "Bedo",
        "Bedotshekha",
        "Choetenkha",
        "Chuthagkha",
        "Darchu",
        "Dardo",
        "Demcho",
        "Dobu",
        "Dolepchen",
        "Dolepchen",
        "Draglu",
        "Dramato",
        "Drangja Goenpa",
        "Dzongdraagkha",
        "Dzongkha",
        "Gadraagna",
        "Gadradazhikha",
        "Gaitsa",
        "Gangchujab",
        "Gangtokha",
        "Gartshangnang",
        "Giutsig",
        "Gonyim",
        "Jagna",
        "Janalungpa",
        "Jangchubtoe",
        "Jangka",
        "Jangka",
        "Jangka Tsekha",
        "Jangkawogma",
        "Jangminang",
        "Jangsa",
        "Jangsarbu",
        "Jangsekha",
        "Jangsipetsa",
        "Jangtoedkha",
        "Jemphu",
        "Jieu",
        "Jungsikha",
        "Kazhi",
        "Kenpalong",
        "Khimchungnang",
        "Kilikha",
        "Lambatoed",
        "Legchukha",
        "Lhakhangnang",
        "Lhakhangokha",
        "Limchen",
        "Linga",
        "Lungpathangkha",
        "Mayukha",
        "Mekhu/Sikhu",
        "Menchu",
        "Naemjog",
        "Naktshangtsawa",
        "Namchikha",
        "Nazhikha",
        "Omchunang",
        "Pangbisa",
        "Para",
        "Pepchu",
        "Poeri",
        "Potokha",
        "Pumnang",
        "Rabsima",
        "Rangetsawa",
        "Rema",
        "Rhidima",
        "Rimpoeri",
        "Riphakha",
        "Sama",
        "Sasa",
        "Serikha",
        "Sharigyurwawog",
        "Sharijekema",
        "Shariling Shingtsa",
        "Shariyurwatakpa",
        "Shingkalachu",
        "Sima",
        "Talung",
        "Tashigang",
        "Temisema",
        "Thangkha",
        "Toechochu",
        "Toechoelu",
        "Tserinang",
        "Tshangpa",
        "Tshaphelo",
        "Tshaphelo",
        "Tshekha",
        "Tshelgona",
        "Tshetekha",
        "Tshoshingtengkha",
        "Ugyenguru",
        "Wochen",
        "Wolinang",
        "Wolithangkha",
        "Woochhu",
        "Woochhu Toed",
        "Woochhu Toed Ngo",
        "Zhelngo",
        "Zhelngo Wogma",
        "Zhingchen",
        "Zhingchen Thangkha",
        "Zhogkukha",
      ],
  
      Naja: [
        "Bemphu",
        "Bueltikha",
        "Jadokha",
        "Jagoen",
        "Jazhina",
        "Jilikha",
        "Lingzhi",
        "Nagu",
        "Pherukha",
        "Rangzhigang",
        "Tabjo",
        "Tokhab",
        "Tshebji",
        "Tshegoen",
        "Tshendu Goenpa",
        "Wanakha",
        "Zursuna",
      ],
  
      Shaba: [
        "Bara",
        "Barakempa",
        "Baratokha",
        "Bjizhikha",
        "Chesham",
        "Chhukha (Shaba)",
        "Drugyaldingkha",
        "Gangjoogkha",
        "Gangri",
        "Khasuna",
        "Lholing",
        "Naychu",
        "Neyphu",
        "Phubarna",
        "Serina",
        "Serlingnang",
        "Tashichholing",
        "Teli",
        "Zhelngo",
        "Zhingo",
        "Zhunggar",
      ],
  
      Tsento: [
        "Chhoeding",
        "Chhungjey",
        "Chuyul",
        "Jiutsaphu",
        "Lemdo",
        "Lemgoen",
        "Mitshig",
        "Nyamed",
        "Nyamjey",
        "Nyechhu",
        "Phangdo",
        "Shana",
        "Shari (Tsento)",
        "Soe Domzang",
        "Soe Yagsa",
        "Tagtshang",
        "Tsatsam",
        "Tshenshi",
        "Yagsa",
        "Zamsar",
      ],
  
      Wangchang: [
        "Baangdey",
        "Baangdey Zam",
        "Barkor",
        "Chang Rouna",
        "Chang Sinchuna",
        "Changkar",
        "Changmedthangka",
        "Chewnang",
        "Chhoeten Dangrim",
        "Chiminang/Chimina",
        "Chintsho",
        "Darzhigang",
        "Dochhukha",
        "Drungna",
        "Dungar",
        "Dungchuphu",
        "Gangkha",
        "Gangkha",
        "Gangtoed",
        "Gebtoed",
        "Gorina",
        "Gyelgang",
        "Jangkhuna",
        "Jangsabu",
        "Jangsina",
        "Jangsuna",
        "Jangteyna",
        "Jieu",
        "Jimnang",
        "Kangjulo",
        "Khangkhu",
        "Khimsabu",
        "Langmana",
        "Langmana",
        "Lankhang Jab",
        "Lomlo",
        "Mendrel",
        "Mendrel/Rauna",
        "Nakha",
        "Nakha/Rawna",
        "Namkar",
        "Nangzhikha (Wangchang)",
        "Naymey",
        "Ngetsu",
        "Nyisu",
        "Nyisu Chotentsawa",
        "Olathang",
        "Omchuna",
        "Pumsima",
        "Pumtakha",
        "Rampozhing",
        "Rawna",
        "Segona",
        "Segona",
        "Sisitagpa",
        "Sisitakpa",
        "Tagokha",
        "Tajoog",
        "Tshogdu (Wangchang)",
        "Tshongdue",
        "Tshshingtsawa",
        "Tsirena",
        "Wochhukha",
        "Wochukha",
        "Yekukha",
        "Yurwawog",
        "Yurwawog",
        "Zakha",
        "Zarchhekha ",
        "Zhikha",
        "Zhingkha",
      ],
    },
  
    Pemagatshel: {
      Chimoong: [
        "Chhimoong",
        "Chhiphoong",
        "Loongkholom",
        "Nyasikhar",
        "Pangthang",
        "Redingla",
      ],
  
      Choekhorling: [
        "Arden",
        "Chhoekhorling",
        "Dizama",
        "Kerong",
        "Yargyewoong",
      ],
  
      Chongshing: [
        "Chongshing",
        "Guyoom",
        "Jorphoong",
        "Maendi",
        "Thongsa",
        "Yomzor",
      ],
  
      Decheling: [
        "Babta",
        "Dechheling Martsala",
        "Doongphu Goenpa",
        "Gonpawoong",
        "Kholomri",
        "Mendelgang",
        "Namdaling",
        "Ridzomo",
        "Rognawang",
        "Shingchongri",
      ],
  
      Dungmaed: [
        "Bangyuel",
        "Belna Goenpa",
        "Belnangzor",
        "Dungmaed",
        "La-Nyiri",
        "Mangthangri",
        "Mikuri",
        "Tep Tep La",
        "Thrumchoong",
        "Tomi",
        "Woonborang",
      ],
  
      Khar: [
        "Bongmaan",
        "Duewang",
        "Khar",
        "Khawar",
        "Khengzor",
        "Labar",
        "Nagtseri",
        "Phadi",
        "Regi",
        "Shemshem",
        "Shinangri",
        "Tsebar",
        "Yagyur",
        "Zordoong",
      ],
  
      Nanong: [
        "Bainangtang",
        "Bargoenpa",
        "Barkadung",
        "Borphu",
        "Champhari",
        "Dapurung",
        "Denphu",
        "Dhalung",
        "Dongtsheri",
        "Drangsa Wong",
        "Gashingkhar",
        "Gayri",
        "Ghorkaling",
        "Jangray",
        "Jazung",
        "Jomgom",
        "Khangmari",
        "Khaykhar",
        "Kheshingri",
        "Kheydong",
        "Kulung",
        "Laypheri",
        "Lumri",
        "Maygamri",
        "Menjung",
        "Menphu",
        "Mongthung",
        "Muna",
        "Nanong",
        "Panglap Thongma",
        "Pangthang",
        "Phalamphu",
        "Raling",
        "Rangshi Gayri",
        "Rangshi Goenpa",
        "Rangthang Wong",
        "Rashu Goenpa",
        "Rayzor",
        "Relung",
        "Sa Yul",
        "Sangshing Tang",
        "Sayri",
        "Sayrimkha",
        "Terphug",
        "Thongshing Gag",
        "Thongthung",
        "Thongthung Goenpa",
        "Thorkhar",
        "Thrangshing",
        "Tokari",
        "Tokari Gayri",
        "Tshatshi",
        "Woongchhillo",
        "Woulingtang",
        "Zhingri",
      ],
  
      Norbugang: [
        "Gashari",
        "Maenchu",
        "Nganglam",
        "Nganglam Bazar",
        "Norboogang",
        "Nyingshingborang",
        "Rinchenzor",
        "Tshaelshingzor",
      ],
  
      Shumar: [
        "Bainangwoong",
        "Bartsheri",
        "Chongmashing",
        "Dagor",
        "Gamung",
        "Goenpoong",
        "Kheri Goenpa",
        "Khothagpa",
        "Nangkhor",
        "Shali",
        "Shumar",
        "Waphel",
        "Yalang",
      ],
      
      Yurung: [
        "Bangdala",
        "Chengri",
        "Dooknang",
        "Doongnang",
        "Doongsingma",
        "Doopkang",
        "Gomtshang",
        "Jarimenang",
        "Joenkha",
        "Khangma",
        "Khominang",
        "Lhawong",
        "Pangthang",
        "Phusumri",
        "Phutsoongbori",
        "Porila",
        "Rezor",
        "Thoonggo",
        "Thoongkhar",
        "Wanglakho",
        "Yangkhar",
      ],
  
      Zobel: [
        "Choongkhar",
        "Lenshingkhar",
        "Ngangmalang",
        "Pangthangdaza",
        "Raysinang",
        "Shumarjug",
        "Tshelinggor",
        "Zobel",
      ],
      Norbugang: [
        "Damzagsa (Dipujora)",
        "Dawaling (Maghay)",
        "Dramzigang (Kataray)",
        "Gangtosa (Kothidara)",
        "Jarigang (Merik)",
        "Khangduzhi (Kopchey)",
        "Kyedsa (Kothidara/Kirney)",
        "Kyidsa (Kirney)",
        "Kyidtsaling (Dhapper)",
        "Labmi (Lamjee)",
        "Lamjosa (Lamjumsa)",
        "Madgang (Gairigaon)",
        "Norboogang (Tinteray)",
        "Thorila Thumkey",
        "Tsaphelthang (Nabukharka)",
        "Tsheringang (Nangla Dang)",
        "Tshongduekha (Hatkhola)",
        "Yangphilthang (Bhimtar)",
      ],
    }, 
  
    Punakha: {
      Barp: [
        "Boemena",
        "Chagsa",
        "Choezhikha",
        "Dechendingkha",
        "Dosega",
        "Gamkha",
        "Gangkha",
        "Gangmaloongma",
        "Geonchhukha",
        "Jaloong",
        "Laphuna",
        "Lobesa",
        "Lumina",
        "Menchuzakha",
        "Mitshigna",
        "Pachheykha",
        "Phuntshoyangkhel",
        "Sebjeekha",
        "Sebtokha",
        "Sobsokha",
        "Tongde Baykha",
        "Tshogkorna",
        "Usakha",
        "Yuwakha",
        "Zhikha",
      ],
  
      Chhubug: [
        "Bali",
        "Bumtakha",
        "Chukhu Ngoedroobchhu",
        "Chuphu Ngoedroobchhu",
        "Humpathang",
        "Jangkholo",
        "Jangwakha",
        "Kepailo",
        " Lhabisa",
        "Lorina",
        "Nawakha",
        "Ngoedroobchhu",
        "Ngoedroobchhu Chukha",
        "Ngoedroobchhu Khimchena",
        "Ngoedroobchhu Tenkha",
        "Puna Gom",
        "Rechena",
        "Sewala",
        "Tenpakha",
        "Yebisa",
      ],
  
      Dzomi: [
        "Changjokha",
        "Danamo",
        "Dzomisa",
        "Gubji",
        "Jangsar",
        "Jangsarbu",
        "Jasha Goenpa",
        "Jimithang",
        "Khilikhar",
        "Likashong",
        "Loongkha",
        "Loongkhajang",
        "Mendagang",
        "Tanag",
        "Thangzhi",
        "Tseykha",
        "Tseykhakha",
        "Uesakha",
        "Yangchenkha",
      ],
  
      Goenshari: [
        "Draagchhukha",
        "Goomgang",
        "Sechednang",
        "Yorbo",
        "Zhelngoesa",
      ],
  
      Guma: [
        "Baymenang",
        "Baypai Gangkha",
        "Bemsesi",
        "Bemsesi Khuru",
        "Botolo",
        "Chokhor Luchhu",
        "Dargaygang",
        "Dawana",
        "Dochhukha",
        "Dochhukha Bangmena",
        "Dochhukha Goenpa",
        "Dochhukha Menchugang",
        "Dochhukha Phaduna",
        "Dochhukha Tongsana",
        "DochhukhaRitsa",
        "Dongkokha Drapchegang",
        "Dongkokha Loongsilgang",
        "Dongkokha Pepchu",
        "Gagona",
        "Gona Tengkha",
        "Guma",
        "Jangchubchen",
        "Jangsa",
        "Khuru Bamsesi Washegang",
        "Khuru Bemsesi",
        "Lakhu",
        "Logodama",
        "Nibji",
        "Nibjiwoma",
        "Semtogangchhu",
        "Tenpakha",
        "Tharabachey",
        "Tongtshasho",
        "Wangwakha",
        "Wolajangsa Gumagangju",
        "Wolakha",
        "Zamdongkhar Bebigacha",
        "Zamdongkhar Bebigar",
        "Zamdongkhar Bebigarkha",
        "Zamdongkhar Changyuel",
        "Zamdongkhar Dongkhuju",
        "Zamdongkhar Gaupay",
        "Zamdongkhar Laykha",
        "Zamdongkhar Logodama",
        "Zamdongkhar Loongsilgang",
        "Zamdongkhar Simtogang",
        "Zamdongkhar Tashijong",
        "Zamdongkhar Thara",
        "Zamdongkhar Zinchey",
        "Zerkha",
      ],
  
      Kabisa: [
        "Agonang",
        "Ap Zhuksa",
        "Bara",
        "Botokha",
        "Chhoeten Nyingpo",
        "Chisegang",
        "Chulukha",
        "Chuzamgang",
        "Damchi",
        "Damteykha",
        "Dokuna",
        "Dokuna sophu",
        "Dophukha",
        "Dzongchung",
        "Haylu Tongshu",
        "Heyloog",
        "Jangsa",
        "Kazhikha",
        "Kelwagang",
        "Lengo Gaysa",
        "Loongtikha",
        "Pangreju",
        "Peltari",
        "Phakakha",
        "Rangrekha",
        "Serigang",
        "Tongchena",
        "Tongshina",
        "Tongshiremay",
        "Tongsigang",
        "Tongzhoonang",
        "Tshetenang",
        "Tshomiding",
        "Uesarkha",
        "Wakhuna",
        "Yurbu",
        "Yuwa",
        "Zarbisa",
        "Zhingsahang",
      ],
  
      Lingmukha: [
        "Dompala",
        "Goomkarmo",
        "Lingmukha",
        "Nabchhed",
        "Oomtekha",
      ],
  
      Shenga: [
        "Bangna Thanka",
        "Bara",
        "Barna Thangka",
        "Chongchog Goenpa",
        "Chongzhikha",
        "Datong Goenpa",
        "Domina",
        "Dubchu Goenpa",
        "Gangchula",
        "Gangkha",
        "Gangla",
        "Garakha",
        "Goen Wogma",
        "Goleygang",
        "Gumena",
        "Japana",
        "Jarigang",
        "Jazhikha",
        "Jimjig",
        "Keparabsel",
        "Khubji",
        "Kutsiphakhar",
        "Langjo",
        "Loigima",
        "Manikha",
        "Menchudamley",
        "Mendrelji",
        "Nangpakha",
        "Norboo Tashi",
        "Nyebakha",
        "Palu",
        "Pangzhi",
        "Shenga Goenpa",
        "Songchumo",
        "Tagochen",
        "Thonji",
        "Tshamkana",
        "Tshosa",
        "Yedogang",
        "Yedopang",
      ],
  
      Talong: [
        "Dongkokhar",
        "Dongkokhar Shongrina",
        "Gangthramo",
        "Gomgang",
        "Jawana",
        "Kidlingkha",
        "Labtsakha",
        "Loongnangkha",
        "Lungtamo",
        "Lungtengang",
        "Lutamo",
        "Norbugang",
        "Norbugang Bemidingkha",
        "Norbugang Bulgang",
        "Norbugang Dashigang",
        "Norbugang Gaupay",
        "Norbugang Lamseri",
        "Norbugang Serinang",
        "Norbugang Tshochuna",
        "Paagchhakha",
        "Pangmarpo",
        "Talog",
        "Talog Goenpa",
        "Yonggu",
        "Zamdongkhar Pangalay",
      ],
  
      Toepisa: [
        "Aechey",
        "Bemsisi",
        "Bichhekha",
        "Bomthangka",
        "Chandana",
        "Chenlekha",
        "Damkhyi",
        "Dochogla",
        "Ghagsa",
        "Goenmkha",
        "Goenmsa",
        "Jaloong",
        "Lemjakha",
        "Lungjam",
        "Maenchhuna",
        "Mendrelgang",
        "Phentekha",
        "Rinakha",
        "Siluna",
        "Stokha",
        "Tang Ho",
        "Thinleygang",
        "Tokha",
        "Toktogkha",
        "Tsheringgang",
        "Yanglo",
        "Yuel Ham O",
      ],
  
      Toewang: [
        "Bederlo",
        "Bidongkha",
        "Bidongkha Tsetending",
        "Chungkha",
        "Dabji",
        "Darshongma",
        "Dawakha",
        "Dawanang",
        "Dengana",
        "Gengo",
        "Jarakha",
        "Jopkha",
        "Kewana",
        "Kutshana",
        "Lebchulo",
        "Limkha",
        "Naripa",
        "Nebtenkha",
        "Omchupang",
        "Pangsho",
        "Raro",
        "Samdingkha",
        "Tamidamchu",
        "Thangji",
        "Tsachuphu",
        "Tsachuphu Kati",
        "Tsachuphugang",
        "Tsephu",
        "Tsephu Atako",
        "Tsephu Bumpai Tsawa",
        "Tsephu Jara",
        "Tsephu Khawakha",
        "Tsephu Semeki",
        "Tsering",
        "Wangkha",
        "Yuesakha",
        "Yusakha Neyji",
      ],
    },
  
    Samdrupjongkhar: {
      Dewathang: [
        "Ashikhar",
        "Bangtsho",
        "Chhenangri",
        "Domphoog",
        "Gerwa",
        "Martang",
        "Rikhey",
      ],
  
      Gomdar: [
        "Amshing",
        "Bargoenpa",
        "Bazor",
        "Belnang Woong",
        "Brongshing",
        "Broomi",
        "Chidoongkhar",
        "Denchhi",
        "Denchhi Khoyar",
        "Fremi",
        "Gomdar",
        "Khandoma",
        "Khoyar",
        "Khoyar Pangthang",
        "Luzor",
        "Narphoong",
        "Palroong",
        "Rechanglu",
        "Rongchanglu",
        "Sawang",
      ],
  
      Langchenphu: [
        "Agoorthang (Aguritar)",
        "Aumshing (Betholi)",
        "Chelthang (Kharbandi/Khowrong)",
        "Damtsang (Daldalay)",
        "Dewathang (Nangley)",
        "Jampani",
        "Jangsawom (Lower Golanti)",
        "Jansagom (Upper Golanti)",
        "Jomotshangkha (Daifam Throm)",
        "Lanchenphu Toed (Upper Hastinapur)",
        "Langchenphu Maed (Lower Hastinapur)",
        "Namchazor (Bajhrangi)",
        "Pagshingkha (Malabasy)",
        "Rongchhuthang (Khowrong)",
      ],
  
      Lauri: [
        "Betseling",
        "Doongmanma",
        "Gonong",
        "Lauri",
        "Momring",
        "Patpanadang",
        "Phajo Goenpa",
        "Relnang",
        "Serzhong",
        "Tashiphu",
        "Tshephu",
        "Tshothang",
        "Woongthig",
      ],
  
      Martshala: [
        "Chhoedoong",
        "Chongmashing",
        "Dengshingzor",
        "Doongmanma",
        "Galingkhar",
        "Gorthongma",
        "Kaeptang",
        "Kakani",
        "Kakpadoong",
        "Khalingdangre/Galingkhar",
        "Loongbaktang",
        "Martshala",
        "Pelrithang",
        "Raushing",
        "Rechanglu",
        "Sarjoong",
        "Shem Shem",
        "Suzor",
        "Thizor",
        "Thongpashing",
        "Tsholingkhar",
        "Tshongpashing",
        "Wargphoog",
      ],
      Orong: [
        "Batshoong",
        "Batshoong",
        "Bilam",
        "Chongti",
        "Durtsun",
        "Gonminang",
        "Jalamwoong",
        "Jangchhubling",
        "Malang",
        "Mandar",
        "Mantsang",
        "Menchari",
        "Milum",
        "Mitseshing",
        "Morong",
        "Nagzor",
        "Nagzor",
        "Phetong",
        "Redumed",
        "Rimoong",
        "Suzoong",
        "Tershiri",
        "Thungshing",
        "Wooling",
        "Wooling",
      ],
      Pemathang: [
        "Bunakha (Majuwa)",
        "Chirtshosa (Kharbandi)",
        "Doongkarling (Dumpha)",
        "Dramzeygang (Kataray)",
        "Kathoobdang (Diklai)",
        "Labtshazor (Deorali)",
        "Lingmayshong (Tarulay)",
        "Loongminang (Gairitar)",
        "Pemathang (Beldara)",
        "Pemathang (Dalim)",
        "Pyertshosa (Kharbandi)",
        "Raling (Phedi)",
        "Uesarna (Nainital)",
        "Warong (Warang)",
        "Yuwathang (Nalapara)",
        "Balamnang (Nakalitar)",
        "Baylamsharang",
        "Chhoetseyung (Daurey)",
        "Chhumaedthang (Gauthalay)",
        "Doongkarling/Dumpha/Gangatay",
        "Drupchhugang (Kubindey)",
        "Karmaling (Kataray)",
        "Khamaedthang/Mansitar",
        "Mendrupling (Bhawaney)",
        "Minjigang (Tekree)",
        "Phuentshogthang/Bakuli",
        "Samdrupchhoeling/Raitar",
        "Selmonang (Koila)",
        "Shangshingzor",
        "Shukuni/Shangshingzor",
        "Thangchu Goenpa/Chotaytar",
        "Thhongsigang (Saureney)",
        "Thongjaling (Jagartala)",
        "Tsangchutham/U. Mansitar",
        "Tshochoong (Bauney)",
        "Tshogskorling (Majuwa)",
        "Zomlaythang (Katikay)",
      ],
  
      Samrang: [
        "Damsagang Maed (Hillay)",
        "Damsagang Toed",
        "Ngangtshothang Maed",
        "Ngangtshothang Toed",
        "Tshoduen (Sathpokari)",
      ],
  
      Serthi: [
        "Barkalangnang",
        "Chasakhar/Maenjiwoong",
        "Chemari",
        "Dangtsho/Serthig",
        "Dekorwoong/Khanduphoog",
        "Deptsang",
        "Dhukha/Monmola",
        "Drenphoog",
        "Goenpa/Monmola",
        "Jab/Khanduphoog",
        "Junme",
        "Khanduphoog",
        "Khuwangka/Monmola",
        "Lamkhabjay/Serthig",
        "Lhakhangzor/Serthig",
        "Maenjiwoong/Khanduphoog",
        "Maenjiwoongpeka/Khanduphoog",
        "Pangthang/Khanduphoog",
        "Pangthang/Monmola",
        "Pangthang/Serthig",
        "Pemagatshel",
        "Phachhog",
        "Phakchu/Khanduphoog",
        "Rebalingbi",
        "Sakari/Khanduphoog",
        "Suskar",
        "Tang Frang/Serthig",
        "Tang Phrang/Khanduphoog",
        "Tangngakpa/Serthig",
        "Tashithang Gyed",
        "Thujaycheling/Monmola",
        "Tokari Goenpa/Serthig",
        "Woong/Khanduphoog",
        "Zor/Monmola",
      ],
  
      Wangphu: [
        "Bayuel",
        "Benporong",
        "Haila",
        "Khainorong/Shogshi",
        "Langnang Ringmo/Wangphoog",
        "Lingsum/Shogshi",
        "Manidangre/Shogshi",
        "Sachhilo",
        "Serchhenmo",
        "Shogshi",
        "Shoguwoong",
        "Shokshi Pangthang",
        "Wangphoog",
      ],
  
    },
  
    Samtse: {
      Denchukha: [
        "Benyekha (Benekha)",
        "Damji (Damjee)",
        "Domchhukha (Bhalukhola)",
        "Drameling (Dhamiley)",
        "Duenchhukha (Denchukha)",
        "Duenchhukha (Gajbee)",
        "Gabji",
        "Gawaling (Baseni)",
        "Gesarling (Boribotey)",
        "Kharzhing (Kadori)",
        "Khempaling (Khempa)",
        "Mayona (Dhamiley)",
        "Phazhing (Beteni)",
        "Poongthra A",
        "Poongthra B",
        "Relukha",
        "Shetakha",
        "Yomeling (Mayona)",
      ],
  
      Dophoogchen: [
        "Aringgang (Tarigaon)",
        "Bamengang (Mithun)",
        "Chhuka (Basantey)",
        "Chilumchen (Chelumchen)",
        "Dangreyboog Ka (Beachgaon A)",
        "Dangreyboog Kha (Beachgoan)",
        "Dograp (Dogap)",
        "Dokarkha Ga (Dorokha C)",
        "Dokarkha Ka (Dorokha A)",
        "Dokarkha Kha (DorokhaB)",
        "Gangtokha (Daragaon)",
        "Jigme",
        "Legpagang (Lapchey Goan)",
        "Manigang (Maney A)",
        "Manigang (Maney B)",
        "Melonggang (Sebichang)",
        "Mizomsa (Somlachen)",
        "Namchu",
        "Ngagang (Damphuchen)",
        "Sangloong",
        "Sengteng",
        "Singye",
        "Tengdelshong (Satakha)",
        "Thingyersa (Timburey)",
        "Thuloonggang",
        "Wangchuck",
      ],
  
      Dungtoe: [
        "Doomtoed (Daragon)",
        "Doomtoed Chhungwa (Sanu Doomtoed)",
        "Doongtoed Chhewa (Thulo Doomtoed)",
        "Gairigaon",
        "Jarikha (Jaringay)",
        "Khaling (Khaling Goan)",
        "Kuzhuggang (Kuchey)",
      ],
  
      "Namgay Chhoeling": [
        "Bepoteng (Belbotey)",
        "Chhoedagling (Choksa)",
        "Chhunaggang (Kalikhola)",
        "Daangling (Pakhagaon)",
        "Dewachen (Shivalaya)",
        "Gangjoog (Chebju)",
        "Gangtog (Gyanthok)",
        "Gyalposhing (Raja Rukh)",
        "Jamcholing (Sajbotey)",
        "Kangdoongphug (Jogimara)",
        "Namgay Chhoeling",
        "Norjangsa (Girigaon)",
        "Pagshingkha (Malbasay)",
        "Peljorling Maed",
        "Peljorling Toed",
        "Satsangsa (Majuwa)",
        "Sernyagang (Kholakharka)",
        "Tashichhoeling (Sipsu)",
        "Tshachhungang (Noonpani)",
        "Tsholingkhar (Pokhari Dara)",
        "Tshosarling (Rangedara)",
        "Zhiwaling (Kothigaon)",
      ],
  
      Norgaygang: [
        "Chhu Goo (Chingu)",
        "Chongzhu",
        "Dangreyboog (Bich Gaon)",
        "Ghundagaon",
        "Guengaling (Ghunday Gaon)",
        "Joenpang",
        "Karmaling (Kamigoan)",
        "Khababgang (Thika)",
        "Linggarnang (Lingtam)",
        "Migphelgang (Dhakalgang)",
        "Norgeygang (Lower Bara)",
        "Noryog",
        "Patshaling (Beteni)",
        "Phendegang (Fenchi)",
        "Samphelgang (Lepchagaon)",
        "Satsangma (Majuwa)",
        "Tshachhu",
        "Zhendebgang (Mukheni Gaon)",
      ],
      Pemaling: [
        "Balsathang (Bimirey)",
        "Beyulgang (Kopchey)",
        "Chhoekorling (Schooley)",
        "Chhoetenkha (Deorali)",
        "Chhujugthang (Chhetritar)",
        "Chhusilgang (Chisopani)",
        "Damtshangna (Ahaley)",
        "Darzhingthng (Jagatar)",
        "Dechengang (Sarki Gaon)",
        "Dizanggang (Kophi)",
        "Dramedsa (Sepeni)",
        "Dramzeling (Kataray)",
        "Gatsheling (Baraney)",
        "Gomsumposa (Tinratey)",
        "Jureygang (Bararay)",
        "Khangzhima (Chargharey)",
        "Komaling (Balsey)",
        "Lamaithang (Lamatar)",
        "Lungsirma (Sirisey)",
        "Lungtensa (Saureni)",
        "Manidara",
        "Manigang (Manidara/Gangtey)",
        "Nakeyling (Nigurey)",
        "Neydagling (Dhamigaon)",
        "Ngadoongsa (Dhengrey)",
        "Norgyeling (Taley)",
        "Nyachhabsa (Gangtey)",
        "Nyadoesa (Katley)",
        "Pangthangjug (Thandey)",
        "Pekarling (Toribari)",
        "Pemaling (Kamigaon)",
        "Phagsamthang (Ghondeytar)",
        "Shing Ngarma (Khamarey)",
        "Singdregang (Jyamirkot)",
        "Tamchhaabsa (Birukhola)",
        "Tashithang (Tachey)",
        "Thangchhenang (Birutar)",
        "Tsajnsa Ka (Hatikhara A)",
        "Tsajnsa Kha (Hatikhara B)",
        "Tsakethang (Samatar)",
        "Yurungthang (Khopitar)",
        "Zamthangnang (Sagutar)",
      ],
  
      "Phuntshog Pelri": [
        "Chhunag (Kalapani)",
        "Chhutharsum (Tindharey)",
        "Dewathang (Banstar)",
        "Doleg (Dholay)",
        "Doomshinggang (Dumshidara)",
        "Gaden (Bhotaykharka)",
        "Gashingma (Gashing)",
        "Goenpakha (Gombadara)",
        "Jangchhogling (Uttarey)",
        "Ketshaelgang (Thotney)",
        "Lachhuthang (Lahatar)",
        "Neygang (Damdara)",
        "Nyoenpaling",
        "Nyoenpaling",
        "Nyoenpaling",
        "Peldenling (Gomtu)",
        "Samerchen (Ratey)",
        "Satergang (Khanigaon)",
        "Satorma (Panray)",
        "Tashilakha (Numilakha)",
        "Tashitshe (Lechi)",
        "Thongjabi (Thumkey)",
        "Tingtingma (Titi)",
        "Uelgyalling (Dolomthang)",
      ],
  
      Samtse: [
        "Bugtognang (Bukkay)",
        "Chathakgang (Sangla)",
        "Chhirlogsa (Chiloo)",
        "Damtshangma (Ahalay)",
        "Dewathang (Banstar)",
        "Dungkarling (Choilicoop)",
        "Gawadong (Sukraty)",
        "Goenpazor (Gombadara)",
        "Jangchhogling (Uttary)",
        "Khandothang (Mechetar)",
        "Kipadong (Sukraty/Bauwandara)",
        "Lamaithang (Lamitar)",
        "Lhakhangpong (Manderlin)",
        "Lingmaithang (Lamatar)",
        "Majathang (Budhuney)",
        "Nyimaling (Saureni)",
        "Serthang (Khalingtar)",
        "Shatshamchhu (Duarpani)",
        "Tsapero (Tasim)",
        "Tshongdzom (Malbasay)",
        "Yulu Maed (Bukay B)",
        "Yulu Toed (Bukay A)",
      ],
  
     " Sangngag Chhoeling": [
        "Bumpathang (Bahunitar)",
        "Chhuchhungsa (Jitti A)",
        "Chhuchhungsa (Jitti B)",
        "Chhuchhungsa (Jitti C)",
        "Chungthung",
        "Depheling Toed (Gathiya A)",
        "Dephelling (Gathiya B)",
        "Dephelling (Gathiya C)",
        "Dephelling (Gathiya D)",
        "Joenlegsa (Setipekha)",
        "Khamzangling (Satvaiya)",
        "Khangchunggang (Pakhadura)",
        "Khangthongsumpa (Tintalay)",
        "Khangzangling (Labarbot)",
        "Kharselling (Mongargaon)",
        "Lingthang (Lengthey)",
        "Namseling",
        "Ngoedroobling (Sombek A)",
        "Ngoedroobling (Sombek B)",
        "Ngoedroobling (Sombek C)",
        "Saduzhima (Chargharay A)",
        "Shaduzhima (Cargharay B)",
        "Tharpung (Tharphu)",
        "Tsangchushong (Latakhola)",
      ],
  
      Tading: [
        "Bugkha (Bucca)",
        "Damzhagsa (Thunuwa)",
        "Dangraybug (Beachgaon)",
        "Domtshang (Balukoray)",
        "Doogpoling (Kamai Banjang)",
        "Gangtokha (Daragaon)",
        "Jinpathang (Deotey)",
        "Khempagang (Khempa Gaon)",
        "Lapchakha",
        "Norjangsa Dangpa (Gairigaon Ek)",
        "Norjangsa Nyipa (Gairigaon Dho)",
        "Nyindooglakha",
        "Panzhing Ghongma (Upper Phanbari)",
        "Panzhing Wogma (Lower Panbari)",
        "Sherabling (Jenchu Gaon)",
        "Tababgang (Tabagaon)",
        "Tading",
        "Tenpaling (Titring)",
        "Thongsa (Ramitey)",
        "Tobchhenthang (Borbotey)",
        "Zochhaling (Sisney)",
      ],
  
      Tendruk: [
        "Chhermaling (Fita)",
        "Dangreybug (Bichgaon)",
        "Dawathang (Jumsatar)",
        "Dawthongsa (Jumsiligaon)",
        "Denpajong (Soureney)",
        "Domdongsa (Balukhop)",
        "Dzongsar",
        "Kachhen (Kachin)",
        "Kangzhima (Chargarey)",
        "Khengtong",
        "Kuchhengang (Kuchin Parkha)",
        "Kuchhenthang (Kuchin Tar)",
        "Kuchhentoed (Kuchin Upper)",
        "Kuengaling (Pakpay)",
        "Miglamthang (N. Bindu)",
        "Miglamthang (N. Bindu)",
        "Nyizergang (Ningalay)",
        "Rangthagling (Jatey)",
        "Silwaithang (Bakbakey)",
        "Targothang (Okhar Botey)",
        "Tendruk",
        "Tendrukthang (Tendu Tar)",
        "Thagpzosa (Dhoreni)",
      ],
  
      Ugentse: [
        "Dangkharling (Bahun Gaon)",
        "Dangreyboog (Bich Gaon A)",
        "Dangreyboog (Bich Gaon A)/Jangsa",
        "Dangreyboog (Bich Gaon B)",
        "Dangreyboog (Bich Gaon)/Khar",
        "Dangreyboog (Bich Gaon)/Tashiding",
        "Dechhengang (Rai Gaon)",
        "Jarip/Ngatshang",
        "Jarithang (Jarip C)",
        "Jarithang Maed (Jarip B)",
        "Jarithang Toed (Jarip A)",
        "Kardog",
        "Kardog",
        "Kardog",
        "Lhendupling (Thakuri Gaon)",
        "Nyimalung (Bhotaykharka)",
        "Rigpaling (Schooldara)",
        "Schooldara/Tashiding",
        "Serigang (Bhotaykharka)",
        "Tharpaling (Majuwa)",
      ],
  
      Yoeseltse: [
        "Choekiling (Gairigaon)",
        "Dungkar (Khumaune B)",
        "Guma (Nau Number)",
        "Jigmedthang (Lamitar)",
        "Kinzangling",
        "Koenchogling (Kuchi Daina)",
        "Pelkithang (Kataharey)",
        "Ranjoongling (Suntalabari)",
        "Richhenphoog (Kharbandi)",
        "Samtenchhu (Khola Ghari)",
        "Sengeyling (Singidara)",
        "Soenakhar",
        "Tsakaling",
        "Tsakaling (Ghumauney A)",
        "Zoepaling (Jarip)",
        "Zurigang (Ghalley Gaon)",
      ],
  
  
    },
  
    Sarpang: {
      Chhudzom: [
        "Azhethang (Ranikhop)",
        "Bachhuthang (Bechkhola)",
        "Chhibigang (Gairigaon)",
        "Chhudzomsa (Dovan)",
        "Chunyethang (Baragaray)",
        "Dechenling (Nunpani)",
        "Dragchhu (Tirkhola)",
        "Galegthang (Ghunring)",
        "Jangchhubling (Pankhey)",
        "Lhayuel (Mougaon)",
        "Mautsangchhu (Maukhola)",
        "Mongarling (Mongergaon)",
        "Norbugang (Khargaon)",
        "Nyachhu (Machukhola)",
        "Pelrigang (Rametey)",
        "Rijugang (Fedi)",
        "Samtenphu (Daragaon)",
        "Sherabling (Pathibara)",
        "Thongjabi (Tarkharkha)",
        "Thselithang (Bhimirey)",
      ], 
  
      Dekiling: [
        "Chhoekhorling (Toribari)",
        "Dabithang (Sukhatar)",
        "Darbithang (Sukhatar)",
        "Dekidling (Leopani)",
        "Dolongang (Gairegoan)",
        "Gawaithang (Kafleytar)",
        "Hamlingphu (Leokhop)",
        "Jigmedling (Chuwabari)",
        "Lungtenbi (Sukhatar)",
        "Menchhuthang (Rateygoan)",
        "Mendelgang (Bichpani)",
        "Norbuthang (Kafleytar)",
        "Nubgang (Dolpani)",
        "Rateypani (Dekiling)",
        "Tashiling (Lampatey)",
        "Yangchenphu (Kafleytar)",
      ], 
   
  
      Gelephu: [
        "Dzamlingthang (Mainator)",
        "Lekidthang (Lakitar)",
        "Pelrithang",
        "Pelrithang (Lodrai)",
        "Pelrithang (Mainatar)",
        "Pelrithang (Somitar)",
        "Pemathang (Somitar)",
      ], 
  
      "Jigme Chhoeling": [
        "Bartsham Ka (Bichgaon A)",
        "Bartsham Kha (Bichgaon B)",
        "Chhoetenkhar (Sukumbasi)",
        "Chungsing",
        "Doringphu (Dungay)",
        "Gakidling (Kholatar)",
        "Galegchhu (Galeychu)",
        "Gongduegang (Gong Gaon)",
        "Gongtsekha (Gongdara)",
        "Hokaling (Gairigaon)",
        "Jungchhurgang (Saudalay)",
        "Khamaed",
        "Khamaed (Daragaon)",
        "Khamo",
        "Khatoed",
        "Khatoed (Sirangaon)",
        "Lungselgang",
        "Mendrelgang (Bhirgaon)",
        "Moenchhukga (Mongergaon)",
        "Pachhakha (Beteni)",
        "Pemagang (Pakhey)",
        "Riti (Reti)",
        "Samkhara",
        "Serbugang (Ashiney)",
        "Shingkharthang (Samkhara)",
        "Silsagang (Casey)",
        "Tagjogang (Babjungay)",
        "Tashigatshel (Chakpai)",
        "Tormaphoog (Tormay)",
        "Tshachhu (Tatopani)",
      ], 
  
      Samtenling: [
        "Chhoekhorling (Majuwa)",
        "Dechenpelri (Jaruwa)",
        "Dechhenpelri (Jaruwa)",
        "Dungkharling",
        "Khenpagang (Dungmindra)",
        "Samtenling (Bhur)",
        "Samtenthang (Juprey)",
        "Samtenthang (Jupreydara)",
      ], 
  
      Senggey: [
        "Chiwaling (Pingkhuwa)",
        "Labtsakha",
        "Nenyul (Sisty)",
        "Peljorling (Kopchey)",
        "Rishong (Sistykhopan)",
        "Sahariphu (Balatung)",
        "Singhi",
        "Tashitsel (Labarbotay)",
        "Wangchuling (Phibsoo)",
        "Yarpheling (Toemba)",
        "Yuejug (Chotatsirang)",
      ], 
  
      Sherxhong: [
        "Barshong (Thaewar)",
        "Kapung (Somitar)",
        "Norbuling",
        "Pangkhar (Somitar)",
        "Pemayoedling",
        "Sherzhong",
        "Tashiphoog",
      ], 
  
      Shompangkha: [
        "Dargyethang (Patabari)",
        "Gadanchholing (Sarpangbazar)",
        "Gomchola Ka (Chaar)",
        "Gomchola Kha (Kharey Pakhey)",
        "Koenchhogling (Kharpanitar)",
        "Norbugang (Akhow)",
        "Risoomgang (Tinjurey)",
        "Shompangkha (Sarpangtar)",
        "Thongjazor (Parkheygoan)",
      ], 
  
      Tarethang: [
        "Dorjitse (Chargery)",
        "Garkhola",
        "Khamartari",
        "Lamitar",
        "Pemachholing (Dragaon)",
        "Singhi Dap",
        "Singhi Dara",
        "Tashichhoeling (Krasheschholing)",
        "Tashichholing",
        "Woongchhilu (Limbutar)",
        "Yoed Zergang (Rangadara)",
      ], 
  
      Umling: [
        "Chubarthang (Chesopani)",
        "Daangling",
        "Daangling (Dhoray)",
        "Daangling (Katesey)",
        "Dungmin",
        "Dungmin (Baraytar)",
        "Dungmin (Bawanitar)",
        "Dungmin (Bichpany)",
        "Dungmin (Bistadara)",
        "Dungmin (Gobritar)",
        "Dungmin (Gurungtar)",
        "Dungmin (Salbandi)",
        "Gaden",
        "Gaden (Proper Lalai)",
        "Gaden (School Dara)",
        "Gaden (Upper Lalai)",
        "Gaden (Upper Lalaidhap)",
        "Lingar",
        "Lingar (Bistadara)",
        "Rijoog",
        "Rijoog",
        "Rijoog (Largkhar)",
        "Rijoog (Tamkuley)",
        "Tashithang",
        "Thongjazor",
        "Semtokha",
        "Olakha",
        "Changedaphu",
      ], 
  
      Chhuzagang: [
        "Barthang",
        "Barthang (Daragoan)",
        "Chagsakhar",
        "Chagsakhar (Danabari)",
        "Chagsakhar (Dawathang)",
        " (Kalikhola)",
        "Chagsakhar (Limbutar)",
        "Chagsakhar (Somitar)",
        "Chagsakhar (Thewar)",
        "Chaskhar (Daragoan)",
        "Nyimaling",
        "Nyimaling (Daragoan)",
        "Nyimaling (Lower Phanphaney)",
        "Pangzor",
        "Pangzor (Danabari)",
        "Pangzor (Daragoan)",
        "Pangzor (Kalikhola)",
        "Pangzor (Upper Phanphaney)",
        "Shawaphoong",
        "Shawaphoong (Daragoan)",
        "Shawaphoong (Lower Phanphaney)",
        "Tongjabi",
        "Tongjabi (Danabari)",
        "Tongjabi (Daragoan)",
        "Tongjabi (Lower Phanphaney)",
        "Tshojan",
        "Tshojan (Lower Phanphaney)",
        "Yueling",
        "Yueling (Danabari)",
        "Yueling (Daragoan)",
        "Yueling (Lower Phanphaney)",
        "Zambabi",
        "Zambabi (Danabari)",
        "Zombabi (Daragoan)",
        "Jigmeling",
      ], 
    },
  
  
    Thimphu: {
      Chang: [
        "Babi Chorten",
        "Debsid",
        "Gangchhe",
        "Jumo",
        "Lhoongtsho",
        "Nezeylhakhang",
        "Ngachuphakha",
        "Rama",
        "Sarbethang",
        "Yoedselpang",
      ], 
   
      Darkala: [
        "Chamgang",
        "Chamgang Toed",
        "Doongdrog",
        "Gyaltala",
        "Wangdrog",
      ], 
   
      Genye: [
        "Chizhi Goenpa",
        "Ge-Nyenkha",
        "Tsho-Chhenkha",
        "Wangbama",
        "Zanglegkha",
      ], 
   
      kawang: [
        "Boegarna",
        "Chhagminang",
        "Chhandragang",
        "Chhoekhor",
        "Dazhi",
        "Dechenphu",
        "Deling Goenpa",
        "Dodennang",
        "Janazampa",
        "Kabisa",
        "Kuzhugchen",
        "Tashiding",
        "Wangkawog",
        "Zhoshuel",
      ], 
   
      Lingzhi: [
        "Chagphu",
        "Chhuzarkha",
        "Gang Yuel",
        "Khangkid Yuel",
        "Sha Yuel",
        "Chumdo",
      ], 
   
      Mewang: [
        "Bemegasa",
        "Chimithangka",
        "Chudingkha",
        "Dalukha",
        "Danglo",
        "Doklaisa",
        "Dolepchen",
        "Dongkarla",
        "Dramesa",
        "Gida",
        "Goenwog",
        "Jadingkha",
        "Jamdo",
        "Jamdo Goma",
        "Jamdo Woma",
        "Jampel",
        "Jiminang",
        "Kepaithang",
        "Kharibji",
        "Kharphu",
        "Khasadrapchu",
        "Khasakha",
        "Lamwog",
        "Langdro",
        "Lingzhipharka",
        "Nyenzerkha",
        "Patsekha",
        "Puleona",
        "Pungzhi",
        "Samakha",
        "Selaykha",
        "Sengyelna/Karphu",
        "Sigay",
        "Silidraphu",
        "Siluna",
        "Simu",
        "Sisinang",
        "Tshaloongna",
        "Tshaphu",
        "Walunang",
        "Zhingsagang",
      ], 
   
      Naro: [
        "Barshong",
        "Chungdulo",
        "Gangbu",
        "Goedshog",
        "Gunglona",
        "Jagoethang",
        "Khasho",
        "Lhayulhaetoed",
        "Moentshiphoog",
        "Naro",
        "Pagoed",
        "Sipchu",
        "Tagsidthang",
        "Walithang",
        "Waza",
        "Zhomthang",
        "Zigu",
      ], 
   
      Soe: [
        "Changmatasa",
        "Damgochong",
        "Dotaapaithang",
        "Dozotoen",
        "Gadraten",
        "Jangothang",
        "Jomphu",
        "Toepgoethang",
      ], 
    },
  Trashigang: {
      Bartsham: [
        "Bainangkhar",
        "Bargoen",
        "Bumling",
        "Chaod Lhakang wog",
        "Dzong Goen",
        "Dzong Thong",
        "Jamoong",
        "Kedpoong",
        "Kumoong",
        "Maentshang",
        "Majadoong",
        "Moogkhar",
        "Nagtshang",
        "Ngaloong",
        "Ngaloong Gang",
        "Pam",
        "Pangthang",
        "Resengma",
        "Reygang",
        "Rophoong",
        "Sershing",
        "Soortshong",
        "Tashi Teng",
        "Thangchey",
        "Trashang",
        "Yangkhar",
        "Zhingom",
        "Zoor",
      ],
  
      Bidung: [
        "Bargoen (Bidung)",
        "Daling",
        "Dodrom",
        "Dori (Bidung)",
        "Gaygoen",
        "Jaloong",
        "Kakaniwog",
        "Khairi",
        "Limphang",
        "Perthong",
        "Retsang Peg",
        "Takseri",
        "Tsekhar",
        "Tsigtoom",
      ],
  
      Kanglung: [
        "Maanthong",
        "Mertsham",
        "Pangthang",
        "Ritsangdoong",
        "Rongthoong",
        "Thargom",
        "Yonphoogla",
        "Yonphoogpam",
      ],
  
      Kangpara: [
        "Bedengphoog",
        "Chorphoog",
        "Dangna",
        "Doyam Chema",
        "Drumshari",
        "Gangpar",
        "Kheri",
        "Kheshing",
        "Lagoen",
        "Lamyong",
        "Langnang",
        "Madeywa",
        "Merdag",
        "Neyling",
        "Passaphoog",
        "Peydoong",
        "Ribalingmi",
        "Sarong",
        "Threlphoog",
        "Yungney",
        "Zordoong",
      ],
  
      Khaling: [
        "Barshong",
        "Bayphoog (Khaling)",
        "Bayphoog Shiri",
        "Brekha",
        "Brekha Doongtshopay",
        "Daksa",
        "Daktsheng",
        "Dangre",
        "Doongthopay",
        "Douzor",
        "Dregoen",
        "Dreywoong",
        "Goenpa",
        "Gomchhu",
        "Jibechhu",
        "Jiri",
        "Khochiphaye",
        "Kholdoong",
        "Lemang",
        "Lemi",
        "Lemi Chhamzor",
        "Liza",
        "Meringzor",
        "Mongkhorla",
        "Rashuwoong",
        "Thrimkhar",
        "Thripang Goenpa",
        "Tokaphu",
        "Tshangpo",
        "Wangachema",
      ],
  
      Lumang: [
        "Bamshing",
        "Bargoenpa (Lumang)",
        "Beamri",
        "Chengri",
        "Darnang",
        "Daroong",
        "Daroong Wadrangzor",
        "Deno",
        "Deno",
        "Doomgmanma",
        "Dori",
        "Dori Tsano",
        "Dubkhang",
        "Dubkhang Goenpa",
        "Gaphoo",
        "Goenzor",
        "Habla",
        "Jabgoen",
        "Jabgoenpa",
        "Khaphe",
        "Khargoen",
        "Kharphoo",
        "Kharphoogoenpa",
        "Kheri (Lumang)",
        "Kheshing (Lumang)",
        "Kheshing Reserbu",
        "Kheshing Roamzor",
        "Kheshingserbu",
        "Khinying Manma",
        "Khomin",
        "Kurchilo",
        "Lumang",
        "Lumang Goenzor",
        "Lumang Gomtshang",
        "Lumang Shachari",
        "Moochhu",
        "Omshari",
        "Ragea",
        "Reserbu",
        "Rizang",
        "Rushingye",
        "Sangmari",
        "Sayuel",
        "Sethang",
        "Shachari",
        "Tashichoedling",
        "Thrimla",
        "Thrumnang",
        "Thrumnang Lishingzor",
        "Tsano",
        "Tshangpo",
        "Wadrangzor",
        "Wamrong",
        "Woongang",
      ],
  
      Merak: [
        "Chelephoo",
        "Gyengo",
        "Khashateng",
        "Khiliphoo",
        "Merag Maed",
        "Merag Toed",
      ],
  
      Phongmed: [
        "Banyalting",
        "Bargoenpa",
        "Brang",
        "Bumtang",
        "Demkhar",
        "Dorshing",
        "Gadzari",
        "Janyema",
        "Karmagoenpa",
        "Kharpa",
        "Lem",
        "Lhakhang",
        "Momnangkhar",
        "Pengtse",
        "Phimshong",
        "Shingkhang",
        "Shingringmo",
        "Soelkhar",
        "Tathrang",
        "Thongrong",
        "Thrang",
        "Yabrang",
        "Yerchiloo",
      ],
  
      Radi: [
        "Boongmaen",
        "Chamang",
        "Chhima",
        "Dekidling",
        "Deling",
        "Doon Goen",
        "Doongsam",
        "Doongshing/Tshatshey",
        "Joenla Tshetshe",
        "Joenlapam",
        "Kadam",
        "Khudumpang",
        "Langteng",
        "Melongkhar",
        "Nagtshang",
        "Pajogoenpa",
        "Pakaling",
        "Pangthang",
        "Radhi Pangthang",
        "Thangthrang",
        "Togshingmang",
        "Tongling Kadam",
        "Tongling Khatoe",
        "Tongling Pam",
        "Tongling Pangthang",
        "Tongling Tangthrang",
        "Tongling Thrang",
        "Tsengkhar",
      ],
  
      Sekteng: [
        "Borangmang",
        "Borangtse",
        "Burnlog",
        "Melam Thoong",
        "Moorbi",
        "Sagteng",
        "Sagteng Joenkhar",
        "Sagteng Manirong",
        "Sagteng Pusa",
        "Sagteng Tenmang",
        "Sagteng Thagthri",
        "Tholong",
        "Youngbazor",
      ],
  
      Samkhar: [
        "Bikhar",
        "Khabti",
        "Maelphel",
        "Pam",
        "Rangshinkhar",
        "Samkhar",
        "Yenangbrangsa",
      ],
  
      Shongphoog: [
        "Chaling",
        "Chhangmi",
        "Galing",
        "Gongtshephangma",
        "Rangjoong",
        "Shongphoog",
        "Yobinang",
      ],
  
      Thrimshing: [
        "Bayphu",
        "Berdoongma",
        "Bongzor",
        "Lam Pangthang",
        "Lhakhang Jab",
        "Phakpari",
        "Phungshing",
        "Ramchong Ma",
        "Ramchongma",
        "Sako",
        "Thoongkhar",
        "Thrimshing",
        "Tsangpo",
        "Yemkhar",
        "Youngdhir",
      ],
  
      Uzorong: [
        "Baepam",
        "Barkazor",
        "Benshingmo",
        "Chhiya",
        "Dangrong",
        "Dayphoog",
        "Dengtsalo",
        "Geangkhar",
        "Gongtsheri",
        "Jomtshang",
        "Lenche",
        "Maenkhar",
        "Mongka",
        "Mongyea",
        "Rizor",
        "Tshedoong",
        "Yerchhilo",
      ],
  
      Yangnyer: [
        "Changzoe",
        "Daliphang",
        "Dambinang",
        "Dargyeling",
        "Duroong",
        "Karthoong",
        "Khardza",
        "Kheri",
        "Leyphoog",
        "Shokang",
        "Yurmoo",
      ],
    },
  
    Trashiyangtse: {
      Bumdeling: [
        "Betsamang",
        "Bomdir",
        "Gangkhardoong",
        "Ngalimang",
        "Pangkhar",
        "Panglewog",
        "Phanteng",
        "Taphel",
        "Tshaling",
        "Wogmanang",
      ],
  
      Jamkhar: [
        "Chhema (Jamkhar)",
        "Domshing",
        "Largyab",
        "Neydrag",
        "Pachhu",
        "Rijoong",
        "Shingkhar",
        "Tag Chhema",
        "Tongla",
        "Yoob",
        "Zor (Jamkhar)",
      ],
  
      Khamdang: [
        "Daka",
        "Dengloom",
        "Dolepchen",
        "Domtshang",
        "Gardung",
        "Karmazom",
        "Khamdang",
        "Kilkhorchen",
        "Koenchobling",
        "Lengkhar",
        "Ngalamang",
        "Nombaring",
        "Pam",
        "Paychateng",
        "Rabdeling",
        "Serpang",
        "Shakshing",
        "Shalli",
        "Shazam",
        "Zharatshi",
      ],
  
      Ramjar: [
        "Aringborang",
        "Bainang-Reb",
        "Bar Dzong",
        "Bawoong",
        "Domtshang",
        "Doongmaen",
        "Gochang",
        "Goenpa",
        "Gongshing",
        "Kakaney",
        "Khalapangthang",
        "Khiri",
        "Lalam",
        "Laybari",
        "Lemrang",
        "Lengbartang",
        "Lushing",
        "Maenshing",
        "Nagtshang",
        "Pangthang",
        "Phairawa",
        "Romang",
        "Shangthang",
        "Tag Dzong",
        "Thongzor",
        "Tsang-Rong",
        "Tsenkang",
        "Tshotsang",
        "Tshurkhar",
        "Tsushing",
        "Woongkhar",
        "Zor (Ramjar)",
        "Zorthoong",
      ],
  
      Toetsho: [
        "Bagpa (Toetsho)",
        "Bangkhabchen",
        "Chaymkhar",
        "Chhemkhar",
        "Choklabtsa",
        "Dagtsa",
        "Dumang",
        "Dungtse",
        "Jangphoogtse",
        "Khi-Nyel",
        "Khoblakhar",
        "Maeldoong",
        "Manam",
        "Nangkhar goenpa",
        "Omba",
        "Pajab",
        "Pangthang Goenpa",
        "Pungthung",
        "Seb",
        "Sengphu",
        "Sertsho",
        "Thangdang",
        "Togshing",
        "Tshengang",
      ],
  
      Tomzhang: [
        "Bagpa (Tomizangsa)",
        "Bainangkhar",
        "Changmadoong",
        "Dongkashing",
        "Dongshing",
        "Dongtoed",
        "Gomkor",
        "Kenmong",
        "Kuenzangling",
        "Lhauzhing",
        "Maenchhu",
        "Memmong",
        "Pang",
        "Toka",
        "Tsangdoong",
        "Wogkhar",
      ],
  
      Yalang: [
        "Baney",
        "Bayling",
        "Bimkhar",
        "Gangkhar",
        "Li-chen",
        "Rabti",
        "Rinzin Toenpang",
        "Rolam",
        "Thragom",
        "Yalang",
        "Bamchang",
      ],
  
      Yangtse: [
        "Baney",
        "Bayling",
        "Bimkhar",
        "Gangkhar",
        "Li-chen",
        "Rabti",
      ],
  
    },
  
    Trongsa: {
      Dragteng: [
        "Changray",
        "Draagteng",
        "Kuenga Rabten",
        "Phelchung",
        "Reyphel",
        "Samchhoeling",
        "Samling Chala",
        "Samling Churak",
        "Samling Churatak",
        "Samling Dangrey",
        "Samling Dara",
        "Samling Gomola",
        "Samling Khamaed",
        "Samling Kikhornang",
        "Samling Kingacholing",
        "Samling Kormaed",
        "Samling Kurbi",
        "Samling Lhakhangjab",
        "Samling Lhakhangwog",
        "Samling Majaling",
        "Samling Maling",
        "Samling Malingbung",
        "Samling Malingjug",
        "Samling Marzhing",
        "Samling Pesinang",
        "Samling Phokchen",
        "Samling Pingkhar",
        "Samling Pisinang",
        "Samling Pongpa",
        "Samling Shangthong",
        "Samling Shangthongjab",
        "Samling Shingkhar",
        "Samling Ta-Dzong",
        "Samling Tangchen",
        "Samling Theling",
        "Samling Tsekunang",
        "Samling Tshajab",
        "Samling Tshokunang",
        "Samling Wangthang",
        "Samling Yumchen",
        "Samling Zarchen",
        "Samling Zhewthang",
        "Tagtse",
        "Tashidingkha",
        "Uesar",
      ],
  
      Korphoog: [
        "Korphoog Maed",
        "Korphoog Toed",
        "Nabi",
        "Nyimzhong Maed",
        "Nyimzhong Toed",
      ],
  
      Langthil: [
        "Baling",
        "Bayzam",
        "Beyling",
        "Dandung",
        "Jangbee",
        "Koshala",
        "Langthil",
        "Ngadak",
        "Ngomey",
        "Pangzor",
        "Phuzor Phumzor",
        "Wangling",
        "Yuling (Langthil)",
      ],
  
      Nubi: [
        "Bemjee",
        "Bji",
        "Bji Pam",
        "Chela",
        "Dangzhing",
        "Darbab",
        "Dorgen",
        "Gagar",
        "Jongthang",
        "Kabab",
        "Karzhong",
        "Pang",
        "Sengm-Bji",
        "Sinphoog",
        "Thang Ngyel",
      ],
  
      Tangsibji: [
        "Chendenbji",
        "Drangla Goenpa",
        "Kaladrame",
        "Kalathrelme",
        "Nyala Goenpa",
        "Tangsibji",
        "Tshangkha",
      ],
    },
  
    Tsirang: {
      Barshong: [
        "Barshong Maed (Gairigang Ka)",
        "Barshong Toed (Gairigang Ka)",
        "Chunyikhang (Baradhurey)",
        "Gairigang Kha (Gairigaon B)",
        "Gangtokha (Daragang)",
        "Toitshang",
      ],
      Dunglegang: [
        "Dangrayboog Maed (Bichgaon Kha)",
        "Dangrayboog Toed (Bichgaon Ka)",
        "Khirithang (Khorsaney)",
        "Lhamoiloongm (Gopini)",
        "Norjangsa (Lalikharka)",
      ],
      Gosarling: [
        "Chokpur",
        "Dzamling Zor (Upper Suntolay)",
        "Dzamlingthang (Lower Lobsibotay)",
        "Pelrithang (Upper Lobsibotay)",
        "Pemathang (Lower Suntolay)",
        "Phuensoomgang (Gairigaon A)",
      ],
      Kikhorthang: [
        "Dekidling (Lower Bockray)",
        "Maenchhana (Mithun)",
        "Nyizergang (Upper Salami)",
        "Sa-Tsangma (Majuwa)",
        "Tashiyangjong (Lower Salami)",
      ],
      Mendrelgang: [
        "Dzamling Zor (Majigaon)",
        "Dzamling Zor (Manikhola)",
        "Dzamling Zor (Sarkigaon)",
        "Mendrelgang (Lamidara)",
        "Pemashong (Sarkigaon)",
        "Riserboo (Rateykhola)",
        "Riserboo A (Kamigaon)",
        "Riserboo B (Kamigaon)",
        "Shamshing Gaden (Manidara)",
        "Tashipang (Gurungaon)",
      ],
      Patshaling: [
        "Chhuzomsa (Bulkay)",
        "Jakhor (Dhanisay)",
        "Munyulsa (Kaligaon)",
        "Pangthang (Pakhay)",
        "Patsaling Toed",
        "Patshaling Maed",
        "Thakorling (Thangray)",
        "Tsakaling (Kalay Kalikhola)",
      ],
      Phuntenchu: [
        "Chhubapsa (Tshangay)",
        "Dhodomchen (Dhapkhola)",
        "Dongtod (Saureni)",
        "Dragithong (S/Melay)",
        "Goentengkha (Baithakey)",
        "Menchhunang (Kharkhola)",
        "Norbuthang (Manitar)",
        "Peljorling (Dhansiri)",
        "Serzhong (Phaleday)",
        "Tashichholing (Burichu)",
        "Tongshigang (T/Melay)",
        "Wangthangling (Jogitar)",
      ],
      Rangthangling: [
        "Charingma (Zulphaygaon)",
        "Darchhargang (Dhajey)",
        "Dawthongsa (Saunay)",
        "Gagaling (Ghaga Goan)",
        "Neymedsa (Nevarey)",
        "Nyimazor (Herabotay)",
        "Rangthangling (Chanautre)",
        "Rangthangling (Chanautre)",
        "Soonkosh",
      ],
      Semjong: [
        "Dangreygang (Daragaon)",
        "Dekidling (Kokray)",
        "Dzomling (Katikey)",
        "Tashiling Maed (Bararay A)",
        "Tashiling Toed (Bararay B)",
      ],
  
      Sergithang: [
        "Norboogang (Mazgaon)",
        "Semdenjong (Teoray)",
        "Sergithang Maed (Lower Sergithang)",
        "Sergithang Toed (Upper Sergithang)",
        "Tashithang (Patale Tar)",
      ],
      Tsholingkhar: [
        "Alenchi (Alaichey)",
        "Droobchhugang (Harpaypani)",
        "Gomsoom (Tintalay)",
        "Tsholingkar Toed (Upper Tshokana)",
        "Tsholingkhar (Kapazhing)",
        "Tsholingkhar Maed (Lower Tshokana)",
      ],
      Tsirangtoe: [
        "Chhuboelsa (Simpani)",
        "Damtshang",
        "Doongkarling (Bouri)",
        "Kabelzhing (Tsheringtoe)",
        "Soentabsa (Dalleni)",
        "Tagthang (Bhaktar)",
        "Tongshingnang (Salleri)",
        "Tsirang Toed",
        "Wangphoo (Dauthrey)",
        "Zomna (Jingay)",
      ],
    },
  
    WangduePhodrang: {
      Athang: [
        "Dzawa",
        "Haragangkha",
        "Jarog-gang",
        "Kago",
        "Lamga",
        "Lawa",
        "Lomtshokha",
        "Lophokha",
        "Nangzhina",
        "Phagtakha",
        "Rockha",
        "Samthang",
      ], 
  
      Bjendag: [
        "Bakakha",
        "Balakha",
        "Bjednagloongpa",
        "Damzhingkhar",
        "Darjeegang",
        "Dekiling",
        "Dongchen",
        "Euchhu",
        "Eusakha",
        "Gangchukhar",
        "Gangmarkhar",
        "Garzhikha",
        "Geyten",
        "Gholaykhar",
        "Gonaloo",
        "Gongthangkha",
        "Goomina",
        "Jagarlingchu",
        "Jangsergang",
        "Jaubamo",
        "Jazhikha",
        "Kaangtegtewa",
        "Kelakha",
        "Khametey",
        "Khatangkhar",
        "Kokojoog",
        "Kokokhar",
        "Lamdogkha",
        "Lamikhar",
        "Lhakhangchen",
        "Loongmo",
        "Loongpa",
        "Loongphugang",
        "Namgyalling",
        "Ngawang",
        "Nyalagang",
        "Okorzhing",
        "Omchheygang",
        "Omkhag",
        "Pangmarchu",
        "Pangmarkhar",
        "Pangmarpo",
        "Pelchhu",
        "Phagpchhusa",
        "Phuentshoggang",
        "Rinchhenling",
        "Sarchhu",
        "Sershongnang",
        "Shokeylog",
        "Shongchuna",
        "Shongtoedkhar",
        "Sisidarkar",
        "Takarkhar",
        "Tarrog",
        "Tarshingtsawa",
        "Tashi Lakha",
        "Tashi Tokha",
        "Thingmakha",
        "Toedkikhar",
        "Toedkikhar",
        "Toekizingkha",
        "Togchennang",
        "Tshangchhekhar",
        "Tshering Pangchu",
        "Tshigkona",
        "Wachhey",
        "Wakha",
        "Zangtegkha",
      ],
      Dangchu: [
        "Bamed",
        "Chhubar Taagm",
        "Chhubarwog",
        "Doenchhoeling",
        "Dogsena",
        "Drongmeed",
        "Gedra Goenpa",
        "Gempang",
        "Godraang",
        "Loomjoog",
        "Norbooding",
        "Phaljorling",
        "Phuentshoggang",
        "Ridag Goenpa",
        "Rigoen",
        "Rithangwog",
        "Selgona",
        "Taagsar",
        "Tashidingkha",
        "Tashigang",
        "Tokaling",
        "Tomla",
        "Uesagang",
        "Zimi",
      ],
  
      Darkar: [
        "Gyapakha",
        "Kamina",
        "Sili",
        "Taagsha",
        "Tsara",
        "Uma Khamaed",
        "Uma Khatoed",
        "Wogyal",
      ],
  
      Gangteng: [
        "Gangteng",
        "Gangteng Tapaiteng",
        "Geyla",
        "Gorgoen",
        "Jangchen",
        "Koomboo",
        "Maang",
        "Saangtana",
        "Uesa",
      ],
  
      "Gasa Tshogom": [
        "Changkha",
        "Dabchheykha",
        "Gangche",
        "Khamaedna",
        "Khatoedkha",
        "Matshig Kha",
        "Matshigpogto",
        "Pasakha",
        "Ternga",
        "Thoukha",
        "Tongzhong",
        "Gikha",
        "Haebisa",
        "Haetshokha",
        "Medpaisa",
        "Shingkhey",
        "Shingkhey",
        "Tabcheykha",
        "Pinsa",
      ],
  
      Kazhi: [
        "Baedrog",
        "Baelpa",
        "Chegidp",
        "Goendep",
        "Kazhi",
        "Komathrang",
        "Lengbi",
        "Lumchey",
      ],
  
      Nahi: [
        "Eusa Gongm",
        "Eusa Wogm",
        "Haebisa",
        "Halued",
        "Khoorjoongla",
        "Nagbisa",
      ],
  
      Nyisho: [
        "Chhaebhakha",
        "Chhedalog",
        "Chitokha",
        "Gangjab",
        "Geylegkha",
        "Goensar",
        "Kuenzangling",
        "Nyishogkha",
        "Pangkha",
        "Pangzhikha",
        "Samtengang",
        "Zampa",
      ],
  
      Phangyul: [
        "Chhoongserkha",
        "Chhung Goen",
        "Domkha",
        "Goenkhar",
        "Koomchhi",
        "Phangyuel",
        "Wampoekhar",
      ],
  
      Phobji: [
        "Chaji",
        "Chemdro",
        "Chumedchen",
        "Damchoelhakhang",
        "Darjeygyab",
        "Dasangsar",
        "Dogsenang",
        "Drangpa",
        "Gang-gyed",
        "Gangphel",
        "Gorphoog",
        "Hapa",
        "Jangchhub Goenpa",
        "Khemdro",
        "Khewang",
        "Kikhorthang",
        "Kilthang",
        "Logchen",
        "Nemphel",
        "Nyimdrosa",
        "Pangsar",
        "Poelam",
        "Ram Sarp",
        "Taenkhegeyrey",
        "Talachen",
        "Taphoog",
        "Taphoog",
        "Tarchen",
        "Tawa",
        "Tshaldar",
        "Yuelego",
        "Zhephoog",
        "Zhibar",
        "Zhilam",
        "Zhugar",
        "Zigzi",
      ],
  
      Ruepisa: [
        "Aaleygang",
        "Agokha",
        "Baegokha",
        "Baeneybi",
        "Beygongma",
        "Chhagtshalkhar",
        "Chhilikha",
        "Chhumigtengkha",
        "Dagphoog",
        "Dagphugyen",
        "Damchen",
        "Damrukha",
        "Dochhoongthoor",
        "Doegorchabsa",
        "Dongphel",
        "Drolmanang",
        "Drongmaed",
        "Golegkhar",
        "Gongkha",
        "Gyala",
        "Jangsanang",
        "Jaserkha",
        "Khamzhog",
        "Khothangkha",
        "Khothangkha Jongphel",
        "Kibloong",
        "Kilkhorthang",
        "Langdo",
        "Loongchoongna",
        "Lungmagang",
        "Marphelkha",
        "Namgayling",
        "Neygo",
        "Neygobara",
        "Nyachhegyekha",
        "Nyalabi",
        "Nyalakha",
        "Nyizergang",
        "Oharkha",
        "Omchen",
        "Omtekha",
        "Oola",
        "Rambigang",
        "Ruechhedkha",
        "Ruemina",
        "Ruetoedkha",
        "Samarkha",
        "Samdrubgang",
        "Samten Goenpa",
        "Sergaykha",
        "Sheley",
        "Sheltogkha",
        "Tashidingkha",
        "Terkana",
        "Toelakha",
        "Tshamchhog",
        "Tshamokha",
        "Tshamonang",
        "Wangduena",
        "Zamding",
        "Zamding Omtekha",
      ],
  
      Sephu: [
        "Boomilog",
        "Booso",
        "Darrilog",
        "Gangchhukha",
        "Langbi",
        "Longmaed",
        "Longtoed",
        "Loobear",
        "Nakha",
        "Nangkha (Sagatenten)",
        "Rabo",
        "Riwanang",
        "Rukoobji",
        "Serthang",
        "Wangdue Goenpa",
        "Zeri",
      ],
  
      Thedtsho: [
        "Gawaphel",
        "Rinchhengang",
        "Tartaloongchu",
        "Thang Goo",
        "Wangjokha",
        "Curlong",
      ],
    },
  
  
    Zhemgang: {
      Bardo: [
        "Bardo",
        "Digala",
        "Khomshar",
        "Langdurbi",
        "Phulabi",
      ], 
      Bjoka: [
        "Barpong",
        "Chabdenba",
        "Dali",
        "Kamati",
        "Trong (Bjokar)",
      ],
      Goshing: [
        "Budhashi",
        "Lamthang",
        "Lichibi",
        "Limapong",
        "Mewangang",
        "Samchheoling",
      ],
      Nangkor: [
        "Buli",
        "Buli Goenpa",
        "Dakphel",
        "Duenmang",
        "Goleng",
        "Jimjong",
        "Kamjong",
        "Kidkhar",
        "Nyakha",
        "Tali",
        "Tsheldang",
        "Zhobleng",
      ],
  
      Nichula: [
        "Jangkhar",
        "Katong",
        "Marangdued",
        "Ngangla Trong",
        "Panbang",
        "Pongchaling",
        "Ribati",
        "Sonamthang",
        "Thinleygang",
        "Yumdang",
      ],
      Phangkhar: [
        "Chabgoen",
        "Chag-Ngar-Zam",
        "Mamong Trong",
        "Panabi",
        "Pantang",
        "Pongchola",
        "Salapong",
        "Shalingtoed",
        "Tadijong",
        "Tashibi",
        "Zangbi",
      ],
      Shingkhar: [
        "Nyimzhong",
        "Radi",
        "Shingkhar",
        "Thajong",
        "Thrisa",
        "Wamling",
        "Zangling",
      ],
      Trong: [
        "Berti",
        "Dangkhar",
        "Gomphu",
        "Soobdrang",
        "Tamag",
        "Trong",
        "Tshanglajong",
        "Zurphel",
      ],
  
    },
}
export default bhutanDzongkhags;